import { FRIES_CUP_CONFIG } from './config'

const zh = {
  startupAria: 'FriesCup 启动',
  bootText: 'FRIES CUP 导播系统',
  startupCreditLine: 'Designed by michaelsky5',
  startupReadyMeta: 'FC SYSTEM',
  communityLicense: '社区使用声明',
  startupKicker: 'FRIES CUP 启动配置',
  consoleTitle: FRIES_CUP_CONFIG.consoleTitle,
  brandTitle: FRIES_CUP_CONFIG.brandName,
  brandSubtitle: FRIES_CUP_CONFIG.editionName,
  brandCredit: 'michaelsky5',
  consoleKicker: FRIES_CUP_CONFIG.consoleTitle,
  productName: FRIES_CUP_CONFIG.brandName,
  productSubtitle: 'FriesCup Broadcast Toolkit',
  startupRail: 'FRIES CUP STARTUP / v0.1',
  projectDefaultName: 'FriesCup Project',
  fixedThemeLabel: 'FC 黄色主题',
  transitionLogoOw: 'FC 标识',
  teamDirectoryDock: '队伍资料库',
  teamDirectoryDockMeta: 'FC SYSTEM',
  teamDirectoryTitle: '队伍资料库',
  teamDirectorySource: '数据源',
  teamDirectoryRefresh: '刷新',
  teamDirectoryRefreshing: '刷新中',
  teamDirectorySearch: '搜索队伍',
  teamDirectorySearchPlaceholder: '队名 / 简称 / 选手',
  teamDirectoryTeams: '队伍',
  teamDirectoryPlayers: '选手',
  teamDirectoryStaff: '工作人员',
  teamDirectoryStatusReady: '已同步',
  teamDirectoryStatusIdle: '未同步',
  teamDirectoryStatusError: '同步失败',
  teamDirectoryStatusLoading: '读取中',
  teamDirectoryUpdatedAt: '更新时间',
  teamDirectoryFetchedAt: '拉取时间',
  teamDirectorySeason: '赛季',
  teamDirectoryVersion: '版本',
  teamDirectoryApplyA: '应用到 A 队',
  teamDirectoryApplyB: '应用到 B 队',
  teamDirectoryOpenBackend: '打开队伍资料后台',
  teamDirectoryBackendMissing: '队伍资料后台尚未配置',
  teamDirectoryEmpty: '暂无队伍数据',
  teamDirectoryNoMatch: '没有匹配队伍',
  teamDirectorySelectTeam: '选择一支队伍',
  teamDirectorySourceRemote: 'FC System Published',
  teamDirectorySourceFallback: 'Static Fallback',
  teamDirectoryConfirmTitle: '应用队伍',
  teamDirectoryConfirmMessage: (side, teamName, currentName) => `将 ${teamName} 应用到 ${side} 队，当前 ${side} 队为 ${currentName || '空'}。继续？`,
  teamDirectoryApplyLog: (side, teamName) => `应用 FC 队伍到 ${side}: ${teamName}`,
  teamDirectoryRefreshLog: count => `刷新 FC 队伍资料库：${count} 支队伍`,
  teamDirectoryRefreshFailedLog: '刷新 FC 队伍资料库失败',
  teamDirectoryUnknownUpdatedAt: '未提供',
  importLegacyWarning: '已识别旧 FC 项目，部分字段已保存到 legacyExtras'
}

const en = {
  startupAria: 'FriesCup startup',
  bootText: 'FRIES CUP Broadcast System',
  startupCreditLine: 'Designed by michaelsky5',
  startupReadyMeta: 'FC SYSTEM',
  communityLicense: 'Community Usage Notice',
  startupKicker: 'FRIES CUP Startup',
  consoleTitle: FRIES_CUP_CONFIG.consoleTitle,
  brandTitle: FRIES_CUP_CONFIG.brandName,
  brandSubtitle: FRIES_CUP_CONFIG.editionName,
  brandCredit: 'michaelsky5',
  consoleKicker: FRIES_CUP_CONFIG.consoleTitle,
  productName: FRIES_CUP_CONFIG.brandName,
  productSubtitle: 'FriesCup Broadcast Toolkit',
  startupRail: 'FRIES CUP STARTUP / v0.1',
  projectDefaultName: 'FriesCup Project',
  fixedThemeLabel: 'FC Yellow Theme',
  transitionLogoOw: 'FC Mark',
  teamDirectoryDock: 'Team Directory',
  teamDirectoryDockMeta: 'FC SYSTEM',
  teamDirectoryTitle: 'Team Directory',
  teamDirectorySource: 'Source',
  teamDirectoryRefresh: 'Refresh',
  teamDirectoryRefreshing: 'Refreshing',
  teamDirectorySearch: 'Search Teams',
  teamDirectorySearchPlaceholder: 'Team / short / player',
  teamDirectoryTeams: 'Teams',
  teamDirectoryPlayers: 'Players',
  teamDirectoryStaff: 'Staff',
  teamDirectoryStatusReady: 'Synced',
  teamDirectoryStatusIdle: 'Not Synced',
  teamDirectoryStatusError: 'Sync Failed',
  teamDirectoryStatusLoading: 'Loading',
  teamDirectoryUpdatedAt: 'Updated At',
  teamDirectoryFetchedAt: 'Fetched At',
  teamDirectorySeason: 'Season',
  teamDirectoryVersion: 'Version',
  teamDirectoryApplyA: 'Apply To Team A',
  teamDirectoryApplyB: 'Apply To Team B',
  teamDirectoryOpenBackend: 'Open Team Backend',
  teamDirectoryBackendMissing: 'Team backend is not configured',
  teamDirectoryEmpty: 'No team data',
  teamDirectoryNoMatch: 'No matching teams',
  teamDirectorySelectTeam: 'Select a team',
  teamDirectorySourceRemote: 'FC System Published',
  teamDirectorySourceFallback: 'Static Fallback',
  teamDirectoryConfirmTitle: 'Apply Team',
  teamDirectoryConfirmMessage: (side, teamName, currentName) => `Apply ${teamName} to Team ${side}. Current Team ${side}: ${currentName || 'empty'}. Continue?`,
  teamDirectoryApplyLog: (side, teamName) => `APPLY FC TEAM ${side}: ${teamName}`,
  teamDirectoryRefreshLog: count => `REFRESH FC TEAM DIRECTORY: ${count} TEAMS`,
  teamDirectoryRefreshFailedLog: 'REFRESH FC TEAM DIRECTORY FAILED',
  teamDirectoryUnknownUpdatedAt: 'Not provided',
  importLegacyWarning: 'Legacy FC project detected; extra fields were preserved in legacyExtras'
}

export const getFriesCupCopyOverrides = language => (language === 'en' ? en : zh)
