const EDITOR_COPY = {
  zh: {
    editor: '编辑台',
    openingDesk: '开场编辑台',
    matchupDesk: '对阵编辑台',
    lineupDesk: '首发编辑台',
    mapDesk: '地图设置编辑台',
    liveDesk: '直播实况编辑台',
    pauseDesk: '暂停编辑台',
    resultDesk: '结果编辑台',
    thanksDesk: '结束致谢编辑台',
    sceneDesk: '场景编辑台',
    eventCopy: '赛事文案',
    eventNameZh: '中文赛事名',
    eventNameEn: '英文赛事名',
    openingCopy: '开场文案',
    visualPackage: '视觉包装',
    eventSubtitle: '赛事全称',
    openingTitle: '开场标题',
    openingSubtitle: '开场副标题',
    statusLabel: '状态标签',
    eventLogo: '赛事 Logo 地址',
    showEventLogo: '显示赛事 Logo',
    interfaceLanguage: '界面语言',
    backgroundImage: '背景图地址',
    backgroundOpacity: '背景图透明度',
    matchInfo: '比赛信息',
    teamInfo: '队伍信息',
    scoreControl: '比分控制',
    teamLogo: '队标地址',
    uploadLogo: '上传',
    invalidLogoFile: '请选择图片文件。',
    teamPreset: '队伍预设',
    logoStatus: 'Logo 状态',
    logoReady: 'Logo 已配置',
    noLogo: '缺 Logo',
    seriesScore: '系列比分',
    editTeam: '编辑队伍',
    close: '关闭',
    upNextControl: '下一场控制',
    teamMatchup: '对阵队伍',
    swapTeams: '换边',
    currentRound: '当前场次',
    currentMapIndex: '地图序号',
    sideStatus: '攻防状态',
    teamAStatus: 'A 队状态',
    teamBStatus: 'B 队状态',
    none: '无',
    attack: '进攻',
    defense: '防守',
    player: '选手',
    role: '职责',
    startingFive: '首发名单',
    hudOptions: 'HUD 显示',
    showHud: '显示 HUD',
    showMap: '显示地图',
    showFt: '显示赛制',
    showStage: '显示阶段',
    showPlayers: '显示选手名',
    showTicker: '显示滚动条',
    tickerMode: '滚动模式',
    tickerText: '滚动文字',
    activeComms: '监听队伍',
    beginInfo: '开场信息',
    showBans: '显示禁用位',
    loop: '循环',
    once: '单次',
    off: '关闭',
    leftTeam: '左队',
    rightTeam: '右队',
    mapFlow: '地图流程',
    mapDisplay: '地图显示',
    mapType: '地图类型',
    picker: '选图',
    winner: '胜方',
    displayMode: '显示模式',
    metaMode: '信息模式',
    banMode: '禁用显示',
    matchSequence: '比赛流程',
    mapPool: '地图池',
    clean: '干净',
    result: '结果',
    full: '完整',
    show: '显示',
    hide: '隐藏',
    time: '时间',
    stage: '阶段',
    teamA: 'A 队',
    teamB: 'B 队',
    scoreA: 'A 队比分',
    scoreB: 'B 队比分',
    assetEmpty: '未配置',
    assetCustom: '自定义',
    assetReady: '已配置',
    showCurrent: '高亮当前',
    lineupAction: '首发动作',
    lineupSide: '展示队伍',
    lineupMode: '展示模式',
    lineupControl: '首发控制',
    activeOutput: '当前输出',
    readyCount: count => `${count} / 5 就绪`,
    collapse: '收起',
    editPlayers: '编辑选手',
    refreshPreview: '刷新预览',
    fullLineup: '整队入场',
    callout: '逐个点名',
    calloutIndex: '点名位置',
    trigger: '触发动画',
    playerHero: '代表英雄',
    avatarUrl: '选手图片',
    compactHud: '紧凑模式',
    sceneSettings: '场景设置',
    title: '标题',
    subtitle: '副标题',
    description: '描述',
    winnerTeam: '胜方队伍',
    mvpPlayer: 'MVP 选手',
    resultNote: '结果备注',
    thanksCopy: '感谢页文案',
    empty: '留空',
    selectPlayer: '选择选手'
  },
  en: {
    editor: 'Editor',
    openingDesk: 'Opening Desk',
    matchupDesk: 'Up Next Desk',
    lineupDesk: 'Lineup Desk',
    mapDesk: 'Map Setup Desk',
    liveDesk: 'Live Desk',
    pauseDesk: 'Technical Pause Desk',
    resultDesk: 'Result Desk',
    thanksDesk: 'Thanks Desk',
    sceneDesk: 'Scene Desk',
    eventCopy: 'Event Copy',
    eventNameZh: 'Chinese Event Name',
    eventNameEn: 'English Event Name',
    openingCopy: 'Opening Copy',
    visualPackage: 'Visual Package',
    eventSubtitle: 'Event Full Name',
    openingTitle: 'Opening Title',
    openingSubtitle: 'Opening Subtitle',
    statusLabel: 'Status Label',
    eventLogo: 'Event Logo URL',
    showEventLogo: 'Show Event Logo',
    interfaceLanguage: 'Interface Language',
    backgroundImage: 'Background Image URL',
    backgroundOpacity: 'Background Opacity',
    matchInfo: 'Match Info',
    teamInfo: 'Team Info',
    scoreControl: 'Score Control',
    teamLogo: 'Team Logo URL',
    uploadLogo: 'Upload',
    invalidLogoFile: 'Select an image file.',
    teamPreset: 'Team Preset',
    logoStatus: 'Logo Status',
    logoReady: 'Logo Ready',
    noLogo: 'No Logo',
    seriesScore: 'Series Score',
    editTeam: 'Edit Team',
    close: 'Close',
    upNextControl: 'Up Next Control',
    teamMatchup: 'Team Matchup',
    swapTeams: 'Swap Teams',
    currentRound: 'Current Round',
    currentMapIndex: 'Map Index',
    sideStatus: 'Side Status',
    teamAStatus: 'Team A Status',
    teamBStatus: 'Team B Status',
    none: 'None',
    attack: 'Attack',
    defense: 'Defense',
    player: 'Player',
    role: 'Role',
    startingFive: 'Starting Five',
    hudOptions: 'HUD Options',
    showHud: 'Show HUD',
    showMap: 'Show Map',
    showFt: 'Show Format',
    showStage: 'Show Stage',
    showPlayers: 'Show Players',
    showTicker: 'Show Ticker',
    tickerMode: 'Ticker Mode',
    tickerText: 'Ticker Text',
    activeComms: 'Comms',
    beginInfo: 'Begin Info',
    showBans: 'Show Bans',
    loop: 'Loop',
    once: 'Once',
    off: 'Off',
    leftTeam: 'Left Team',
    rightTeam: 'Right Team',
    mapFlow: 'Map Flow',
    mapDisplay: 'Map Display',
    mapType: 'Map Type',
    picker: 'Picker',
    winner: 'Winner',
    displayMode: 'Display Mode',
    metaMode: 'Meta Mode',
    banMode: 'Ban Display',
    matchSequence: 'Match Sequence',
    mapPool: 'Map Pool',
    clean: 'Clean',
    result: 'Result',
    full: 'Full',
    show: 'Show',
    hide: 'Hide',
    time: 'Time',
    stage: 'Stage',
    teamA: 'Team A',
    teamB: 'Team B',
    scoreA: 'Team A Score',
    scoreB: 'Team B Score',
    assetEmpty: 'Empty',
    assetCustom: 'Custom',
    assetReady: 'Ready',
    showCurrent: 'Highlight Current',
    lineupAction: 'Lineup Action',
    lineupSide: 'Lineup Side',
    lineupMode: 'Lineup Mode',
    lineupControl: 'Lineup Control',
    activeOutput: 'Active Output',
    readyCount: count => `${count} / 5 Ready`,
    collapse: 'Collapse',
    editPlayers: 'Edit Players',
    refreshPreview: 'Refresh Preview',
    fullLineup: 'Full Lineup',
    callout: 'Callout',
    calloutIndex: 'Callout Slot',
    trigger: 'Trigger Animation',
    playerHero: 'Signature Hero',
    avatarUrl: 'Player Image',
    compactHud: 'Compact Mode',
    sceneSettings: 'Scene Settings',
    title: 'Title',
    subtitle: 'Subtitle',
    description: 'Description',
    winnerTeam: 'Winner',
    mvpPlayer: 'MVP Player',
    resultNote: 'Result Note',
    thanksCopy: 'Thanks Copy',
    empty: 'Empty',
    selectPlayer: 'Select Player'
  }
}

const getEditorCopy = language => EDITOR_COPY[language] || EDITOR_COPY.en

const LIVE_EDITOR_COPY = {
  zh: {
    liveCoreControl: '导播核心控制',
    teamControl: side => `${side} 队控制台`,
    teamPreset: '队伍预设',
    noPreset: '当前项目队伍',
    teamA: 'A 队',
    teamB: 'B 队',
    lineup: '名单',
    callout: '点名',
    winner: '获胜',
    attackShort: '进攻',
    defenseShort: '防守',
    sideStatus: '攻防状态',
    lockTeamFields: '锁定队伍资料',
    unlockTeamFields: '解锁队伍资料',
    lock: '锁定',
    unlock: '解锁',
    banTitle: 'BAN',
    banSlot: 'BAN 位',
    banOrder: 'BAN 顺序',
    aFirst: 'A 队先 BAN',
    aSecond: 'A 队后 BAN',
    bFirst: 'B 队先 BAN',
    bSecond: 'B 队后 BAN',
    clearBan: '清空 BAN',
    liveTriggers: '动态触发器',
    scoreControl: '比分控制',
    voiceComms: '队内语音',
    autoBegin: '自动入场',
    nameInfo: '选手名牌',
    banMode: 'BAN 模式',
    resetScore: '重置',
    resetScoreLabel: '重置比分',
    resetConfirm: '确认？',
    reset: '重置',
    clear: '清空',
    key: '关键',
    sub: '替补',
    in: '上场',
    currentPlayers: '场上选手',
    banPhase: 'BAN 阶段',
    closeBan: '关闭 BAN',
    tickerControl: '滚动条控制',
    tickerOn: '开启滚动条',
    tickerOff: '关闭滚动条',
    tickerPlaceholder: '输入底部滚动条文本...',
    liveSetup: '实况设置',
    liveMode: '实况模式',
    genericMode: '通用',
    tournamentMode: '赛事',
    topEventCapsule: '顶部赛事胶囊',
    showEventLogo: '显示赛事 Logo',
    showFtLabel: '显示赛制标签',
    centerText: '中心文字',
    logoSource: 'Logo 来源',
    ftLabel: '赛制标签',
    auto: '自动',
    eventAction: '赛事',
    hudYOffset: '实况 Y 偏移',
    teamNameSize: '队名字号',
    playerNameSize: '选手字号',
    eventLogoBg: '赛事 Logo 背景',
    teamALogoBg: 'A 队 Logo 背景',
    teamBLogoBg: 'B 队 Logo 背景',
    teamStatus: '队伍状态',
    statusHiddenNote: '已从直播实况隐藏',
    teamAWins: 'A 队胜场',
    teamALosses: 'A 队负场',
    teamBWins: 'B 队胜场',
    teamBLosses: 'B 队负场',
    teamASeed: 'A 队种子',
    teamBSeed: 'B 队种子',
    teamALabel: 'A 队标签',
    teamBLabel: 'B 队标签',
    displayMode: '显示模式',
    hidden: '隐藏',
    record: '战绩',
    seed: '种子',
    custom: '自定义',
    clearStatus: '清空状态',
    playerSlot: index => `P${index + 1}`
  },
  en: {
    liveCoreControl: 'Live Core Control',
    teamControl: side => `Team ${side} Control`,
    teamPreset: 'Team Preset',
    noPreset: 'Current Project Team',
    teamA: 'Team A',
    teamB: 'Team B',
    lineup: 'Lineup',
    callout: 'Callout',
    winner: 'Winner',
    attackShort: 'ATK',
    defenseShort: 'DEF',
    sideStatus: 'Side Status',
    lockTeamFields: 'Lock Team DB fields',
    unlockTeamFields: 'Unlock emergency Team DB edit',
    lock: 'Lock',
    unlock: 'Unlock',
    banTitle: 'BAN',
    banSlot: 'BAN Slot',
    banOrder: 'BAN Order',
    aFirst: 'A First',
    aSecond: 'A Second',
    bFirst: 'B First',
    bSecond: 'B Second',
    clearBan: 'Clear BAN',
    liveTriggers: 'Live Triggers',
    scoreControl: 'Score Control',
    voiceComms: 'Voice Comms',
    autoBegin: 'Auto Begin',
    nameInfo: 'Name Info',
    banMode: 'BAN Mode',
    banPhase: 'BAN Phase',
    closeBan: 'Close BAN',
    resetScore: 'Reset Score',
    resetScoreLabel: 'Reset Score',
    resetConfirm: 'Sure?',
    reset: 'Reset',
    clear: 'Clear',
    key: 'Key',
    sub: 'Sub',
    in: 'In',
    tickerControl: 'Ticker Control',
    tickerOn: 'Ticker On',
    tickerOff: 'Ticker Off',
    tickerPlaceholder: 'Enter ticker text...',
    currentPlayers: 'Players On Field',
    liveSetup: 'Live Setup',
    liveMode: 'Live Mode',
    genericMode: 'Generic',
    tournamentMode: 'Tournament',
    topEventCapsule: 'Top Event Capsule',
    showEventLogo: 'Show Event Logo',
    showFtLabel: 'Show FT Label',
    centerText: 'Center Text',
    logoSource: 'Logo Source',
    ftLabel: 'FT Label',
    auto: 'Auto',
    eventAction: 'Event',
    hudYOffset: 'Live Y Offset',
    teamNameSize: 'Team Name Size',
    playerNameSize: 'Player Name Size',
    eventLogoBg: 'Event Logo BG',
    teamALogoBg: 'Team A Logo BG',
    teamBLogoBg: 'Team B Logo BG',
    teamStatus: 'Team Status',
    statusHiddenNote: 'Hidden from Live HUD',
    teamAWins: 'Team A W',
    teamALosses: 'Team A L',
    teamBWins: 'Team B W',
    teamBLosses: 'Team B L',
    teamASeed: 'Team A Seed',
    teamBSeed: 'Team B Seed',
    teamALabel: 'Team A Label',
    teamBLabel: 'Team B Label',
    displayMode: 'Display Mode',
    hidden: 'Hidden',
    record: 'Record',
    seed: 'Seed',
    custom: 'Custom',
    clearStatus: 'Clear Status',
    playerSlot: index => `P${index + 1}`
  }
}

const MAP_EDITOR_COPY = {
  zh: {
    matchControl: '比赛控制',
    format: '赛制',
    current: '当前',
    score: '比分',
    total: '总数',
    officialPoolMatrix: '官方地图池矩阵',
    typeCount: (enabled, total) => `${enabled}/${total} 类型`,
    activeMaps: '可用地图',
    typeStatus: '类型状态',
    enabledTypes: count => `${count} 开启`,
    mapCount: count => `${count} 张地图`,
    on: '开',
    off: '关',
    resetPool: '重置地图池',
    addMap: '添加地图',
    reset: '重置',
    delete: '删除',
    map: '地图',
    mode: '类型',
    name: '名称',
    pick: '选图',
    winner: '胜方',
    ban: 'BAN',
    selectFromPool: '从地图池选择',
    live: '直播',
    mapNumber: index => `地图 ${index}`,
    close: '关闭',
    draw: '平局',
    set: '已设置',
    tbd: '待定',
    setCurrent: '设为当前',
    useLiveBans: '使用直播 BAN',
    clearBans: '清空 BAN',
    mapBan: '单图 BAN',
    attackSide: '进攻方',
    order: '顺序',
    aFirst: 'A 先',
    bFirst: 'B 先',
    teamABan: 'A 队 BAN',
    teamBBan: 'B 队 BAN'
  },
  en: {
    matchControl: 'Match Control',
    format: 'Format',
    current: 'Current',
    score: 'Score',
    total: 'Total',
    officialPoolMatrix: 'Official Pool Matrix',
    typeCount: (enabled, total) => `${enabled}/${total} Types`,
    activeMaps: 'Active Maps',
    typeStatus: 'Type Status',
    enabledTypes: count => `${count} On`,
    mapCount: count => `${count} Maps`,
    on: '开',
    off: '关',
    resetPool: 'Reset Pool',
    addMap: 'Add Map',
    reset: 'Reset',
    delete: 'Del',
    map: 'Map',
    mode: 'Mode',
    name: 'Name',
    pick: 'Pick',
    winner: 'Winner',
    ban: 'BAN',
    selectFromPool: 'Select from pool',
    live: 'LIVE',
    mapNumber: index => `MAP ${index}`,
    close: 'Close',
    draw: 'Draw',
    set: 'SET',
    tbd: 'TBD',
    setCurrent: 'Set Current',
    useLiveBans: 'Use Live Bans',
    clearBans: 'Clear Bans',
    mapBan: 'Map BAN',
    attackSide: 'Attack Side',
    order: 'Order',
    aFirst: 'A First',
    bFirst: 'B First',
    teamABan: 'Team A BAN',
    teamBBan: 'Team B BAN'
  }
}

const getLiveEditorCopy = language => LIVE_EDITOR_COPY[language] || LIVE_EDITOR_COPY.en
const getMapEditorCopy = language => MAP_EDITOR_COPY[language] || MAP_EDITOR_COPY.en

const CASTER_EDITOR_COPY = {
  zh: {
    sceneCopy: '解说席包装',
    activeCasters: '出镜解说',
    casterPool: '解说资料库',
    addCaster: '新增解说',
    casterName: '解说名称',
    casterTitle: '解说身份',
    casterSocial: '社交 / 备注',
    casterAvatar: '解说图片',
    casterSlot: index => `解说 ${index + 1}`,
    staffPackage: '制作团队包装',
    staffSlots: '制作团队槽位',
    staffName: '成员名称',
    staffRole: '成员职责',
    staffImage: '成员图片',
    staffDefaultName: index => `成员 ${index + 1}`,
    casterDefaultName: index => `解说 ${index + 1}`,
    defaultStaffTitle: '制作',
    defaultCasterTitle: '解说',
    slot: '槽位',
    visible: '显示',
    visibleUpper: '显示',
    slots: '槽位',
    packageLabel: '包装',
    capacity: '容量',
    scene: '场景',
    eventLogo: '赛事 Logo',
    portraits: '头像',
    titles: '身份',
    slotNumbers: '槽位编号',
    lowerThirdControl: '字幕条控制',
    modeBus: '模式总线',
    contextMode: '比赛信息',
    interviewMode: '采访',
    deskNoteMode: '导播备注',
    offMode: '关闭',
    state: '状态',
    active: '启用',
    source: '来源',
    match: '比赛',
    manual: '手动',
    none: '无',
    contextSource: '比赛信息来源',
    preview: '预览',
    teams: '队伍',
    score: '比分',
    map: '地图',
    ban: 'BAN',
    bans: count => `${count} 个 BAN`,
    payload: '输出内容',
    contextLine: '比赛信息行',
    interviewBuilder: '采访构建',
    speakerMode: '发言人模式',
    speakerPlayer: '选手',
    speakerRep: '代表',
    speakerTeam: '队伍',
    interviewTeam: '采访队伍',
    teamA: 'A 队',
    teamB: 'B 队',
    target: '目标',
    autoManual: '自动 / 手动',
    playerFallback: '选手',
    roleFallback: '职责',
    teamFallback: side => `${side} 队`,
    teamSpeaker: team => `${team} 队伍`,
    repSpeaker: team => `${team} 代表`,
    teamStatement: '队伍声明',
    teamRepresentative: '队伍代表',
    title: '标题',
    speakerName: '发言人名称',
    speakerRole: '发言人身份',
    deskNote: '导播备注',
    load: '载入',
    clear: '清空',
    on: '开',
    off: '关',
    staffSceneFallback: '制作团队',
    castersSceneFallback: '解说席',
    remove: '删除'
  },
  en: {
    sceneCopy: 'Caster Package',
    activeCasters: 'On-air Casters',
    casterPool: 'Caster Library',
    addCaster: 'Add Caster',
    casterName: 'Caster Name',
    casterTitle: 'Caster Title',
    casterSocial: 'Social / Note',
    casterAvatar: 'Caster Image',
    casterSlot: index => `Caster ${index + 1}`,
    staffPackage: 'Staff Package',
    staffSlots: 'Staff Slots',
    staffName: 'Staff Name',
    staffRole: 'Staff Role',
    staffImage: 'Staff Image',
    staffDefaultName: index => `Staff ${index + 1}`,
    casterDefaultName: index => `Caster ${index + 1}`,
    defaultStaffTitle: 'Production',
    defaultCasterTitle: 'Commentator',
    slot: 'Slot',
    visible: 'Visible',
    visibleUpper: 'VISIBLE',
    slots: 'SLOTS',
    packageLabel: 'PACKAGE',
    capacity: 'CAPACITY',
    scene: 'SCENE',
    eventLogo: 'Event Logo',
    portraits: 'Portraits',
    titles: 'Titles',
    slotNumbers: 'Slot Numbers',
    lowerThirdControl: 'Lower Third Control',
    modeBus: 'Mode Bus',
    contextMode: 'Context',
    interviewMode: 'Interview',
    deskNoteMode: 'Desk Note',
    offMode: 'Off',
    state: 'State',
    active: 'Active',
    source: 'Source',
    match: 'Match',
    manual: 'Manual',
    none: 'None',
    contextSource: 'Context Source',
    preview: 'Preview',
    teams: 'Teams',
    score: 'Score',
    map: 'Map',
    ban: 'Ban',
    bans: count => `${count} Bans`,
    payload: 'Payload',
    contextLine: 'Context Line',
    interviewBuilder: 'Interview Builder',
    speakerMode: 'Speaker Mode',
    speakerPlayer: 'Player',
    speakerRep: 'Rep',
    speakerTeam: 'Team',
    interviewTeam: 'Interview Team',
    teamA: 'Team A',
    teamB: 'Team B',
    target: 'Target',
    autoManual: 'Auto / Manual',
    playerFallback: 'Player',
    roleFallback: 'Role',
    teamFallback: side => `Team ${side}`,
    teamSpeaker: team => `${team} Team`,
    repSpeaker: team => `${team} Rep`,
    teamStatement: 'Team Statement',
    teamRepresentative: 'Team Representative',
    title: 'Title',
    speakerName: 'Speaker Name',
    speakerRole: 'Speaker Role',
    deskNote: 'Desk Note',
    load: 'Load',
    clear: 'Clear',
    on: 'ON',
    off: 'OFF',
    staffSceneFallback: 'STAFF',
    castersSceneFallback: 'CASTERS',
    remove: 'Remove'
  }
}

const getCasterEditorCopy = language => CASTER_EDITOR_COPY[language] || CASTER_EDITOR_COPY.en

const ROSTER_EDITOR_COPY = {
  zh: {
    sceneCopy: '阵容包装',
    teamDatabase: '队伍库',
    teamTarget: '展示队伍',
    teamInfo: '队伍信息',
    playerList: '选手阵容',
    staff: '工作人员',
    teamLabel: '队伍',
    slots: '槽位',
    active: '输出',
    tank: '坦克',
    damage: '输出',
    support: '支援',
    sortRole: '按职责排序',
    reset: '重置',
    slot: '槽位',
    dragToReorder: '拖动排序',
    portraitX: '头像 X',
    resetPortraitX: '重置头像 X 到 50%',
    loadImage: '载入',
    max: '上限',
    outputMaxHint: '阵容输出已达到 7 人。',
    saveTeamDb: '保存',
    addPlayer: '新增选手',
    removePlayer: '移除',
    battleTag: 'BattleTag',
    primaryHero: '代表英雄',
    manager: '经理',
    coach: '教练',
    themeColor: '主题',
    show: '显示',
    hide: '隐藏',
    on: '开',
    off: '关',
    ok: '确定',
    teamDbKicker: '队伍库',
    rosterKicker: '阵容',
    teamDbSaved: '队伍库已保存',
    teamDbUpdated: '队伍库已更新',
    teamDbSavedActiveMessage: teamLabel => `${teamLabel} 已是当前队伍库记录，阵容顺序和队伍资料已保存。`,
    teamDbUpdatedMessage: teamLabel => `${teamLabel} 已用当前阵容页数据覆盖，同名重复队伍已移除。`,
    teamDbSavedMessage: '当前队伍已保存到队伍库。',
    teams: '队伍',
    players: '选手',
    search: '搜索',
    searchPlaceholder: '缩写 / 队伍 / 选手',
    exportDb: '导出队伍库',
    importDb: '导入队伍库',
    sortTeams: '排序队伍',
    addTeam: '新增队伍',
    short: '缩写',
    teamName: '队伍名',
    roster: '阵容',
    roles: '职责',
    status: '状态',
    action: '操作',
    roleSummary: counts => `坦${counts.tank || 0} / 输${counts.damage || 0} / 辅${counts.support || 0}`,
    staffCount: count => `${count} 人`,
    matchSlot: slots => `比赛 ${slots.join(' / ')}`,
    library: '队伍库',
    edit: '编辑',
    deleteShort: '删除',
    noMatchingTeams: '没有匹配队伍',
    close: '关闭',
    add: '新增',
    loadA: '载入 A 队',
    loadB: '载入 B 队',
    delTeam: '删除队伍',
    deleteTeamTitle: '删除队伍',
    deleteTeamMessage: teamLabel => `删除 ${teamLabel} 和所有阵容选手？此操作不可撤回。`,
    delete: '删除',
    cancel: '取消',
    importTeamDbTitle: '导入队伍库',
    importTeamDbMessage: count => `导入 ${count} 支队伍并替换当前队伍库？当前队伍和选手阵容都会被替换。`,
    import: '导入',
    importFailedTitle: '导入失败',
    invalidTeamDb: '无效的队伍库文件。',
    defaultTeamName: number => `Team ${number}`,
    defaultPlayerName: number => `Player ${number}`
  },
  en: {
    sceneCopy: 'Roster Package',
    teamDatabase: 'Team Database',
    teamTarget: 'Display Team',
    teamInfo: 'Team Info',
    playerList: 'Roster Players',
    lineupOutput: 'Lineup Output',
    takeFullLineup: 'Take Full Lineup',
    takeCallout: 'Take Callout',
    staff: 'Staff',
    teamLabel: 'Team',
    slots: 'Slots',
    active: 'Active',
    tank: 'Tank',
    damage: 'Damage',
    support: 'Support',
    sortRole: 'Sort Role',
    reset: 'Reset',
    slot: 'Slot',
    dragToReorder: 'Drag to reorder',
    portraitX: 'X%',
    resetPortraitX: 'Reset portrait X to 50%',
    loadImage: 'Load',
    max: 'MAX',
    outputMaxHint: 'Roster output is already at 7 players.',
    saveTeamDb: 'Save',
    addPlayer: 'Add Player',
    removePlayer: 'Remove',
    battleTag: 'BattleTag',
    primaryHero: 'Signature Hero',
    manager: 'Manager',
    coach: 'Coach',
    themeColor: 'Theme',
    show: 'Show',
    hide: 'Hide',
    on: 'ON',
    off: 'OFF',
    ok: 'OK',
    teamDbKicker: 'Team DB',
    rosterKicker: 'Roster',
    teamDbSaved: 'Team DB Saved',
    teamDbUpdated: 'Team DB Updated',
    teamDbSavedActiveMessage: teamLabel => `${teamLabel} is already the active Team DB record. Current roster order and team fields are saved.`,
    teamDbUpdatedMessage: teamLabel => `${teamLabel} was overwritten with the current roster page data. Duplicate same-name entry was removed.`,
    teamDbSavedMessage: 'Current team has been saved to Team DB.',
    teams: 'Teams',
    players: 'Players',
    search: 'Search',
    searchPlaceholder: 'Short / team / player',
    exportDb: 'Export DB',
    importDb: 'Import DB',
    sortTeams: 'Sort Teams',
    addTeam: 'Add Team',
    short: 'Short',
    teamName: 'Team Name',
    roster: 'Roster',
    roles: 'Roles',
    status: 'Status',
    action: 'Action',
    roleSummary: counts => `T${counts.tank || 0} / D${counts.damage || 0} / S${counts.support || 0}`,
    staffCount: count => `${count} Staff`,
    matchSlot: slots => `Match ${slots.join(' / ')}`,
    library: 'Library',
    edit: 'Edit',
    deleteShort: 'Del',
    noMatchingTeams: 'No matching teams',
    close: 'Close',
    add: 'Add',
    loadA: 'Load A',
    loadB: 'Load B',
    delTeam: 'Del Team',
    deleteTeamTitle: 'Delete Team',
    deleteTeamMessage: teamLabel => `Delete ${teamLabel} and all roster players? This cannot be undone.`,
    delete: 'Delete',
    cancel: 'Cancel',
    importTeamDbTitle: 'Import Team DB',
    importTeamDbMessage: count => `Import ${count} teams and replace the current Team DB? Current teams and roster players will be replaced.`,
    import: 'Import',
    importFailedTitle: 'Import Failed',
    invalidTeamDb: 'Invalid Team DB file.',
    defaultTeamName: number => `Team ${number}`,
    defaultPlayerName: number => `Player ${number}`
  }
}

const COUNTDOWN_EDITOR_COPY = {
  zh: {
    sceneCopy: '倒计时包装',
    breakSetup: '中场设置',
    breakMode: '中场模式',
    standbyMode: '待机',
    countdownMode: '倒计时',
    videoMode: '纯净视频',
    timer: '倒计时控制',
    minutes: '分钟',
    seconds: '秒',
    statusText: '等待文案',
    finishedText: '结束文案',
    startTimer: '重启',
    startTimerLabel: '重置并开始倒计时',
    stopTimer: '停止',
    stopTimerLabel: '停止计时',
    showMatchCard: '显示比赛卡片',
    showLogo: '显示 Logo',
    showEvent: '显示赛事',
    showStatus: '显示状态',
    showSchedule: '显示赛程',
    noCleanVideo: '无纯净视频',
    cleanVideoHint: '在媒体播放 / 纯净视频中设置当前来源',
    toolkitPlayback: '工具播放',
    obsSource: 'OBS 来源',
    queueStatus: (count, mode) => `${count} 个队列 / ${mode}`,
    scheduleSlots: '赛程槽位',
    scheduleHeader: (visible, total) => `${visible} 启用 / ${total} 固定槽位`,
    scheduleHint: '点击比赛编辑内容',
    matchSlot: index => `比赛 ${index + 1}`,
    scheduleSlot: '赛程槽位',
    unconfiguredSlot: '未配置',
    tbdTeam: 'TBD',
    useCurrentMatch: '填入当前比赛',
    clearSlot: '清空槽位',
    logoA: state => `A 队 Logo - ${state}`,
    logoB: state => `B 队 Logo - ${state}`,
    bgA: 'A 队背景',
    bgB: 'B 队背景'
  },
  en: {
    sceneCopy: 'Break Package',
    breakSetup: 'Break Setup',
    breakMode: 'Break Mode',
    standbyMode: 'Standby',
    countdownMode: 'Countdown',
    videoMode: 'Video',
    timer: 'Timer Control',
    minutes: 'Minutes',
    seconds: 'Seconds',
    statusText: 'Standby Text',
    finishedText: 'Finished Text',
    startTimer: 'Restart',
    startTimerLabel: 'Reset and Start Timer',
    stopTimer: 'Stop',
    stopTimerLabel: 'Stop Timer',
    showMatchCard: 'Show Match Card',
    showLogo: 'Show Logo',
    showEvent: 'Show Event',
    showStatus: 'Show Status',
    showSchedule: 'Show Schedule',
    noCleanVideo: 'No Clean Video',
    cleanVideoHint: 'Set an active source in Media Desk / Clean Video',
    toolkitPlayback: 'Toolkit Playback',
    obsSource: 'OBS Source',
    queueStatus: (count, mode) => `${count} queue / ${mode}`,
    scheduleSlots: 'Schedule Slots',
    scheduleHeader: (visible, total) => `${visible} ON / ${total} fixed slots`,
    scheduleHint: 'Click a match to edit',
    matchSlot: index => `Match ${index + 1}`,
    scheduleSlot: 'Schedule Slot',
    unconfiguredSlot: 'Unconfigured',
    tbdTeam: 'TBD',
    useCurrentMatch: 'Use Current Match',
    clearSlot: 'Clear Slot',
    logoA: state => `Logo A - ${state}`,
    logoB: state => `Logo B - ${state}`,
    bgA: 'BG A',
    bgB: 'BG B'
  }
}

const getRosterEditorCopy = language => ROSTER_EDITOR_COPY[language] || ROSTER_EDITOR_COPY.en
const getCountdownEditorCopy = language => COUNTDOWN_EDITOR_COPY[language] || COUNTDOWN_EDITOR_COPY.en

const POST_EDITOR_COPY = {
  zh: {
    pausePackage: '技术暂停包装',
    pauseContext: '暂停上下文',
    statusLabel: '状态标签',
    showMatchFrame: '显示比赛信息框',
    resultPackage: '结果包装',
    winnerActions: '胜负控制',
    setWinnerA: 'A 队获胜',
    setWinnerB: 'B 队获胜',
    clearWinner: '清除胜方',
    resultControl: '赛果控制',
    resultSource: '来源',
    winnerFollowsScore: '胜方跟随比分',
    finalScore: '最终比分',
    scoreAndMvp: '比分与 MVP',
    thanksPackage: '结束页包装',
    thanksCredits: '结束页信息',
    showSummary: '显示赛事总结',
    showCredits: '显示制作信息',
    outputSummary: '输出摘要',
    event: '赛事',
    round: '场次',
    casters: '解说'
  },
  en: {
    pausePackage: 'Tech Pause Package',
    pauseContext: 'Pause Context',
    statusLabel: 'Status Label',
    showMatchFrame: 'Show Match Frame',
    resultPackage: 'Result Package',
    winnerActions: 'Winner Control',
    setWinnerA: 'Team A Wins',
    setWinnerB: 'Team B Wins',
    clearWinner: 'Clear Winner',
    resultControl: 'Result Control',
    resultSource: 'Source',
    winnerFollowsScore: 'Winner follows score',
    finalScore: 'Final Score',
    scoreAndMvp: 'Score and MVP',
    thanksPackage: 'Thanks Package',
    thanksCredits: 'Thanks Credits',
    showSummary: 'Show Event Summary',
    showCredits: 'Show Credits',
    outputSummary: 'Output Summary',
    event: 'Event',
    round: 'Round',
    casters: 'Casters'
  }
}

const getPostEditorCopy = language => POST_EDITOR_COPY[language] || POST_EDITOR_COPY.en

const EDITOR_CHROME_COPY = {
  zh: {
    take: 'TAKE',
    titles: {
      matchup: '流程包装编辑台',
      'starting-five': '流程包装编辑台',
      roster: '队伍阵容编辑台',
      stats: '比赛数据编辑台',
      countdown: '中场控制编辑台',
      casters: '解说席编辑台',
      media: '媒体编辑台',
      'team-data': '选手数据编辑台',
      mvp: 'MVP 编辑台',
      'current-map': '地图设置编辑台',
      'live-hud': '直播实况编辑台',
      pause: '中场控制编辑台',
      result: '流程包装编辑台',
      thanks: '流程包装编辑台'
    },
    dataCenterModes: [
      { id: 'stats', label: '比赛数据', meta: '队伍面板' },
      { id: 'team-data', label: '选手数据', meta: '选手对比' },
      { id: 'mvp', label: 'MVP', meta: '奖项包装' }
    ],
    showFlowModes: [
      { id: 'matchup', label: '下一场', meta: '对阵卡' },
      { id: 'starting-five', label: '首发', meta: '首发名单' },
      { id: 'result', label: '赛果', meta: '赛后包装' },
      { id: 'thanks', label: '感谢页', meta: '收尾包装' }
    ],
    breakDeskModes: [
      { id: 'countdown', label: '中场休息', meta: '待机倒计时' },
      { id: 'pause', label: '技术暂停', meta: '比赛暂停' }
    ],
    casterModes: [
      { id: 'casters', label: '解说', meta: '解说包装', packageMode: 'CASTERS' },
      { id: 'staff', label: '工作人员', meta: '制作团队', packageMode: 'STAFF' }
    ],
    liveModes: [
      { id: 'match', label: '直播控制', meta: '播出信息' },
      { id: 'package', label: '实况设置', meta: '样式状态' }
    ],
    mapModes: [
      { id: 'pool', label: '地图池', meta: '地图类型' },
      { id: 'flow', label: '地图流程', meta: '比赛顺序' }
    ],
    rosterModes: [
      { id: 'roster', label: '阵容', meta: 'A / B 队' },
      { id: 'teams', label: '队伍库', meta: '全部队伍' }
    ],
    mediaModes: [
      { id: 'HIGHLIGHT', label: '高光画面', meta: 'OBS 叠加层' },
      { id: 'VIDEO', label: '纯净视频', meta: '视频输出' }
    ]
  },
  en: {
    take: 'TAKE',
    titles: {
      matchup: 'Show Flow Desk',
      'starting-five': 'Show Flow Desk',
      roster: 'Team Roster Desk',
      stats: 'Match Stats Desk',
      countdown: 'Break Desk',
      casters: 'Caster Desk',
      media: 'Media Desk',
      'team-data': 'Player Data Desk',
      mvp: 'MVP Desk',
      'current-map': 'Map Setup Desk',
      'live-hud': 'Live Desk',
      pause: 'Break Desk',
      result: 'Show Flow Desk',
      thanks: 'Show Flow Desk'
    },
    dataCenterModes: [
      { id: 'stats', label: 'Match Stats', meta: 'Team board' },
      { id: 'team-data', label: 'Player Data', meta: 'Player / H2H' },
      { id: 'mvp', label: 'MVP', meta: 'Award stinger' }
    ],
    showFlowModes: [
      { id: 'matchup', label: 'Up Next', meta: 'Match card' },
      { id: 'starting-five', label: 'Lineup', meta: 'Starting five' },
      { id: 'result', label: 'Result', meta: 'Post-match' },
      { id: 'thanks', label: 'Thanks', meta: 'Closing' }
    ],
    breakDeskModes: [
      { id: 'countdown', label: 'Break', meta: 'Standby / timer' },
      { id: 'pause', label: 'Tech Pause', meta: 'Match hold' }
    ],
    casterModes: [
      { id: 'casters', label: 'Casters', meta: 'Talent package', packageMode: 'CASTERS' },
      { id: 'staff', label: 'Staff', meta: 'Crew package', packageMode: 'STAFF' }
    ],
    liveModes: [
      { id: 'match', label: 'Live Control', meta: 'On-air facts' },
      { id: 'package', label: 'HUD Setup', meta: 'Style / status' }
    ],
    mapModes: [
      { id: 'pool', label: 'Map Pool', meta: 'Map types' },
      { id: 'flow', label: 'Map Flow', meta: 'Sequence' }
    ],
    rosterModes: [
      { id: 'roster', label: 'Roster', meta: 'Team A / B' },
      { id: 'teams', label: 'Team DB', meta: 'All teams' }
    ],
    mediaModes: [
      { id: 'HIGHLIGHT', label: 'Highlight', meta: 'OBS overlay' },
      { id: 'VIDEO', label: 'Clean Video', meta: 'Video output' }
    ]
  }
}

const getEditorChromeCopy = language => EDITOR_CHROME_COPY[language] || EDITOR_CHROME_COPY.en

const PAGE_EDITOR_COPY = {
  zh: {
    statsPackage: '数据包装',
    statsDataInput: '数据输入',
    statsMetricBoard: '指标面板',
    statsMapStore: '地图数据仓',
    imageInput: '图片输入',
    uploadDropPaste: '上传 / 拖拽 / 粘贴',
    ocrCapture: 'OCR 捕获',
    clearImage: '清空图片',
    imageCrop: '图片裁切',
    input: '输入',
    imageReady: '图片就绪',
    manual: '手动',
    preview: '预览',
    rows: '行数',
    screenshotOutput: '截图输出',
    teamBoardOutput: '队伍面板输出',
    dataFeed: '数据源',
    dataSource: '数据来源',
    currentMap: '当前地图',
    mapTotal: '地图累计',
    followMvpType: '跟随类型',
    statsDataLabel: data => (
      data?.scope === 'current'
        ? '当前数据'
        : data?.scope === 'cumulative'
          ? `${data?.snapshots?.length || 0} MAP 汇总`
          : data?.label || ''
    ),
    captureData: '捕获数据',
    savedDataPreview: '保存数据预览',
    shownCount: count => `${count}/6 显示`,
    min: '分钟',
    ocrReady: 'OCR 就绪',
    show: '显示',
    stat: '数据项',
    statLabel: stat => ({
      eliminations: '消灭',
      assists: '助攻',
      deaths: '死亡',
      damage: '伤害',
      healing: '治疗',
      mitigated: '承伤'
    })[stat?.key] || stat?.label || '',
    state: '状态',
    on: 'ON',
    off: 'OFF',
    shown: '已显示',
    hidden: '隐藏',
    saveCurrentMap: '保存当前地图',
    clearOcrRows: '清空 OCR 行',
    exportJson: '导出 JSON',
    exportCsv: '导出 CSV',
    clearStore: '清空仓库',
    time: '时间',
    metrics: '指标',
    saved: '已保存',
    view: '查看',
    deleteShort: '删除',
    noSavedMapData: '暂无地图数据',
    clearSavedMaps: '清空保存地图',
    clearSavedMapsMessage: count => `删除 ${count} 条已保存地图数据？当前输入会保留。`,
    current: '当前',
    savedScope: '保存',
    total: '汇总',
    metricsMode: '指标',
    imageMode: '图片',
    graphicControl: '图形控制',
    valueMode: '数值模式',
    teamScope: '队伍范围',
    cardTag: '卡片标签',
    package: '包装',
    source: '来源',
    playerBuilder: '选手构建',
    matchupBuilder: '对位构建',
    graphicOutput: '图形输出',
    hero: '英雄',
    rosterDefault: '阵容默认',
    default: '默认',
    leftPlayer: '左侧选手',
    rightPlayer: '右侧选手',
    swapPlayers: '交换选手',
    player: '选手',
    playerRows: '选手行',
    rowCount: count => `${count}/5 行`,
    rowPairCount: (teamA, teamB) => `${teamA}/5 // ${teamB}/5`,
    rowComparison: (left, right) => `${left}/5 VS ${right}/5`,
    teamA: 'A 队',
    teamB: 'B 队',
    per10: '每 10 分',
    totals: '总计',
    spotlight: '单人焦点',
    matchup: '对位',
    star: '明星',
    focus: '焦点',
    key: '关键',
    mvpControl: 'MVP 控制',
    mvpType: 'MVP 类型',
    mapMvp: '地图 MVP',
    matchMvp: '全场 MVP',
    packageCopy: '包装文案',
    title: '标题',
    mvpNote: 'MVP 备注',
    awardStats: '获奖数据',
    rosterHero: '阵容英雄',
    highlightOutput: '高光输出',
    showLabel: '显示标签',
    highlightLabel: '高光标签',
    videoControl: '视频控制',
    activeVideoSource: '当前视频源',
    defaultVideoSource: '视频源',
    uploadDropPasteVideo: '上传 / 拖拽 / 粘贴',
    videoSource: '视频源',
    activeVideoPath: '当前视频路径',
    legacySource: '旧版来源',
    useSource: '使用来源',
    selectFile: '选择文件',
    clear: '清空',
    renderMode: '渲染模式',
    muted: '静音',
    loop: '循环',
    mode: '模式',
    mediaModeLabel: value => (String(value || '').toUpperCase() === 'VIDEO' ? '纯净视频' : '高光画面'),
    active: '当前',
    ready: '就绪',
    empty: '空',
    queue: '队列',
    cleanVideoQueue: '纯净视频队列',
    queued: count => `${count} 个队列`,
    noActiveVideo: '无当前视频',
    startQueue: '开始队列',
    videoName: '视频名称',
    videoPath: '视频路径',
    addVideo: '添加视频',
    playlist: '播放列表',
    playbackOrder: '播放顺序',
    library: '素材库',
    registeredSources: '已登记来源',
    playing: '播放中',
    play: '播放',
    up: '上移',
    down: '下移',
    remove: '移除',
    queueVerb: '加入队列',
    queuedState: '已入队',
    delete: '删除',
    noPlaylistItems: '暂无播放项',
    noPlaylistItemsHint: '从素材库加入视频，或直接播放当前路径。',
    noRegisteredVideos: '暂无登记视频',
    noRegisteredVideosHint: '上传视频或登记本地路径。',
    toolkitPlayback: '工具播放',
    obsSource: 'OBS 来源',
    dataCapture: '数据捕获',
    statsOcrDesk: '数据截图 / OCR 工作台',
    close: '关闭',
    cancel: '取消',
    cropPreview: '裁切预览',
    noCropPreview: '暂无裁切预览',
    pasteDropUploadScreenshot: '粘贴、拖拽或上传截图',
    zoomSourceScreenshot: '放大源截图',
    uploadScreenshot: '上传截图',
    zoomOcrCropPreview: index => `放大 OCR 裁切预览 ${index + 1}`,
    zoomPlayerIdScreenshot: (team, index) => `放大 ${team} P${index + 1} ID 截图`,
    zoomPlayerRowScreenshot: (team, index) => `放大 ${team} P${index + 1} 数据截图`,
    cropZones: '裁切区域',
    swapTeams: '交换队伍',
    autoOcr: '自动 OCR',
    timePreview: '时间预览',
    noTimeCrop: '暂无时间裁切',
    zoomTimeCrop: '放大时间裁切',
    cropZonesFirst: '先裁切区域再预览时间',
    status: '状态',
    resetCrop: '重置裁切',
    clearData: '清空数据',
    cropCalibration: '裁切校准',
    statsCrop: '数据',
    timeCrop: '时间',
    playerCrop: '选手',
    timeXPct: '时间 X%',
    timeYPct: '时间 Y%',
    timeWPct: '时间 W%',
    timeHPct: '时间 H%',
    playerXPct: '选手 X%',
    playerWPct: '选手 W%',
    scale: '倍率',
    xPct: 'X%',
    wPct: 'W%',
    hPct: 'H%',
    topPct: 'Top%',
    bottomPct: 'Bottom%',
    threshold: '阈值',
    externalOcrText: '外部 OCR 文本',
    manualFallback: '手动兜底',
    ocrTextPlaceholder: '在这里粘贴 OCR 文本。A 队在前，B 队在后，中间用空行或 --- 分隔。',
    parseText: '解析文本',
    dataTime: '数据时长',
    dataReady: minutes => `${minutes} 分钟数据就绪`,
    applyData: '应用数据',
    closeImagePreview: '关闭图片预览',
    unassigned: '未分配',
    lines: count => `${count} 行`,
    mapNumber: index => `地图 ${index}`,
    statusImageReady: '图片就绪',
    statusWaitingImage: '等待图片',
    statusCropPresetReset: '裁切已重置',
    statusInvalidImage: '图片无效',
    statusImageLoaded: '图片已载入',
    statusCropReady: '裁切就绪',
    statusCropFailed: '裁切失败',
    statusPreparingOcr: '准备 OCR',
    statusTeamRow: (team, row) => `${team} 第 ${row} 行`,
    statusRowOcrComplete: '行 OCR 完成',
    statusOcrFailed: 'OCR 失败',
    statusTextParsed: '文本已解析',
    ocrWorkerStatus: status => String(status || '').toUpperCase()
  },
  en: {
    statsPackage: 'Stats Package',
    statsDataInput: 'Data Input',
    statsMetricBoard: 'Metric Board',
    statsMapStore: 'Map Data Store',
    imageInput: 'Image Input',
    uploadDropPaste: 'Upload / drop / paste',
    ocrCapture: 'OCR Capture',
    clearImage: 'Clear Image',
    imageCrop: 'Image Crop',
    input: 'Input',
    imageReady: 'Image Ready',
    manual: 'Manual',
    preview: 'Preview',
    rows: 'Rows',
    screenshotOutput: 'Screenshot output',
    teamBoardOutput: 'Team board output',
    dataFeed: 'Data Feed',
    dataSource: 'Data Source',
    currentMap: 'Current Map',
    mapTotal: 'Map Total',
    followMvpType: 'Follow Type',
    statsDataLabel: data => data?.label || '',
    captureData: 'Capture data',
    savedDataPreview: 'Saved data preview',
    shownCount: count => `${count}/6 Shown`,
    min: 'Min',
    ocrReady: 'OCR Ready',
    show: 'Show',
    stat: 'Stat',
    statLabel: stat => stat?.label || '',
    state: 'State',
    on: 'On',
    off: 'Off',
    shown: 'Shown',
    hidden: 'Hidden',
    saveCurrentMap: 'Save Current Map',
    clearOcrRows: 'Clear OCR Rows',
    exportJson: 'Export JSON',
    exportCsv: 'Export CSV',
    clearStore: 'Clear Store',
    time: 'Time',
    metrics: 'Metrics',
    saved: 'Saved',
    view: 'View',
    deleteShort: 'Del',
    noSavedMapData: 'No saved map data',
    clearSavedMaps: 'Clear Saved Maps',
    clearSavedMapsMessage: count => `Delete ${count} saved map data ${count === 1 ? 'entry' : 'entries'}? Current input will stay available.`,
    current: 'Current',
    savedScope: 'Saved',
    total: 'Total',
    metricsMode: 'Metrics',
    imageMode: 'Image',
    statMetrics: 'Manual Metrics',
    metricLabel: 'Metric Label',
    teamAValue: 'Team A Value',
    teamBValue: 'Team B Value',
    addMetric: 'Add Metric',
    removeMetric: 'Remove',
    mediaPackage: 'Media Package',
    mediaMode: 'Media Mode',
    videoMode: 'Video',
    mediaUrl: 'Media URL',
    headline: 'Headline',
    playerName: 'Player Name',
    note: 'Interface Note',
    teamDataPackage: 'Player Data Package',
    graphicControl: 'Graphic Control',
    valueMode: 'Value Mode',
    teamScope: 'Team Scope',
    cardTag: 'Card Tag',
    package: 'Package',
    source: 'Source',
    playerBuilder: 'Player Builder',
    matchupBuilder: 'Matchup Builder',
    graphicOutput: 'Graphic Output',
    hero: 'Hero',
    rosterDefault: 'Roster Default',
    default: 'Default',
    leftPlayer: 'Left Player',
    rightPlayer: 'Right Player',
    swapPlayers: 'Swap Players',
    player: 'Player',
    playerRows: 'Player Rows',
    rowCount: count => `${count}/5 Rows`,
    rowPairCount: (teamA, teamB) => `${teamA}/5 // ${teamB}/5`,
    rowComparison: (left, right) => `${left}/5 VS ${right}/5`,
    teamA: 'Team A',
    teamB: 'Team B',
    per10: 'Per 10',
    totals: 'Totals',
    spotlight: 'Spotlight',
    matchup: 'Matchup',
    star: 'Star',
    focus: 'Focus',
    key: 'Key',
    mvpControl: 'MVP Control',
    mvpType: 'MVP Type',
    mapMvp: 'Map MVP',
    matchMvp: 'Match MVP',
    packageCopy: 'Package Copy',
    title: 'Title',
    mvpNote: 'MVP Note',
    awardStats: 'Award Stats',
    rosterHero: 'Roster Hero',
    highlightOutput: 'Highlight Output',
    showLabel: 'Show Label',
    highlightLabel: 'Highlight Label',
    videoControl: 'Video Control',
    activeVideoSource: 'Active video source',
    defaultVideoSource: 'Video Source',
    uploadDropPasteVideo: 'Upload / Drop / Paste',
    videoSource: 'Video source',
    activeVideoPath: 'Active Video Path',
    legacySource: 'Legacy Source',
    useSource: 'Use Source',
    selectFile: 'Select File',
    clear: 'Clear',
    renderMode: 'Render Mode',
    muted: 'Muted',
    loop: 'Loop',
    mode: 'Mode',
    mediaModeLabel: value => (String(value || '').toUpperCase() === 'VIDEO' ? 'Clean Video' : 'Highlight'),
    active: 'Active',
    ready: 'Ready',
    empty: 'Empty',
    queue: 'Queue',
    cleanVideoQueue: 'Clean Video Queue',
    queued: count => `${count} Queued`,
    noActiveVideo: 'No Active Video',
    startQueue: 'Start Queue',
    videoName: 'Video Name',
    videoPath: 'Video Path',
    addVideo: 'Add Video',
    playlist: 'Playlist',
    playbackOrder: 'Playback order',
    library: 'Library',
    registeredSources: 'Registered sources',
    playing: 'Playing',
    play: 'Play',
    up: 'Up',
    down: 'Down',
    remove: 'Remove',
    queueVerb: 'Queue',
    queuedState: 'Queued',
    delete: 'Delete',
    noPlaylistItems: 'No Playlist Items',
    noPlaylistItemsHint: 'Add videos from the library, or play an active path directly.',
    noRegisteredVideos: 'No Registered Videos',
    noRegisteredVideosHint: 'Upload a video or register a local path.',
    toolkitPlayback: 'Toolkit Playback',
    obsSource: 'OBS Source',
    dataCapture: 'Data Capture',
    statsOcrDesk: 'Stats Screenshot / OCR Desk',
    close: 'Close',
    cancel: 'Cancel',
    cropPreview: 'Crop Preview',
    noCropPreview: 'No Crop Preview',
    pasteDropUploadScreenshot: 'Paste, drop, or upload screenshot',
    zoomSourceScreenshot: 'Zoom source screenshot',
    uploadScreenshot: 'Upload screenshot',
    zoomOcrCropPreview: index => `Zoom OCR crop preview ${index + 1}`,
    zoomPlayerIdScreenshot: (team, index) => `Zoom ${team} player ${index + 1} ID screenshot`,
    zoomPlayerRowScreenshot: (team, index) => `Zoom ${team} player ${index + 1} screenshot`,
    cropZones: 'Crop Zones',
    swapTeams: 'Swap Teams',
    autoOcr: 'Auto OCR',
    timePreview: 'Time Preview',
    noTimeCrop: 'No Time Crop',
    zoomTimeCrop: 'Zoom time crop',
    cropZonesFirst: 'Crop zones to preview time',
    status: 'Status',
    resetCrop: 'Reset Crop',
    clearData: 'Clear Data',
    cropCalibration: 'Crop Calibration',
    statsCrop: 'Stats',
    timeCrop: 'Time',
    playerCrop: 'Player',
    timeXPct: 'Time X%',
    timeYPct: 'Time Y%',
    timeWPct: 'Time W%',
    timeHPct: 'Time H%',
    playerXPct: 'Player X%',
    playerWPct: 'Player W%',
    scale: 'Scale',
    xPct: 'X%',
    wPct: 'W%',
    hPct: 'H%',
    topPct: 'Top%',
    bottomPct: 'Bottom%',
    threshold: 'Threshold',
    externalOcrText: 'External OCR Text',
    manualFallback: 'Manual Fallback',
    ocrTextPlaceholder: 'Paste OCR text here. Put Team A first, Team B second. Separate teams with a blank line or ---.',
    parseText: 'Parse Text',
    dataTime: 'Data Time',
    dataReady: minutes => `${minutes} MIN DATA READY`,
    applyData: 'Apply Data',
    closeImagePreview: 'Close image preview',
    unassigned: 'Unassigned',
    lines: count => `${count} Lines`,
    mapNumber: index => `MAP ${index}`,
    statusImageReady: 'IMAGE READY',
    statusWaitingImage: 'WAITING FOR IMAGE',
    statusCropPresetReset: 'CROP PRESET RESET',
    statusInvalidImage: 'INVALID IMAGE',
    statusImageLoaded: 'IMAGE LOADED',
    statusCropReady: 'CROP READY',
    statusCropFailed: 'CROP FAILED',
    statusPreparingOcr: 'PREPARING OCR',
    statusTeamRow: (team, row) => `${team} ROW ${row}`,
    statusRowOcrComplete: 'ROW OCR COMPLETE',
    statusOcrFailed: 'OCR FAILED',
    statusTextParsed: 'TEXT PARSED',
    ocrWorkerStatus: status => String(status || '').toUpperCase()
  }
}

const getPageEditorCopy = language => PAGE_EDITOR_COPY[language] || PAGE_EDITOR_COPY.en

export {
  getEditorCopy,
  getLiveEditorCopy,
  getMapEditorCopy,
  getCasterEditorCopy,
  getRosterEditorCopy,
  getCountdownEditorCopy,
  getPostEditorCopy,
  getEditorChromeCopy,
  getPageEditorCopy
}
