const COPY = {
  zh: {
    kicker: 'OWBT 本地资料',
    title: '素材仓库',
    subtitle: '长期保存队伍、阵容与导播素材，并为 OBS 导播台生成两队对阵包。',
    back: '返回',
    saveCurrent: '保存当前项目队伍',
    importBackup: '导入队伍库备份',
    exportBackup: '导出队伍库备份',
    createTeam: '新建队伍',
    guideButton: '使用流程',
    guideKicker: 'OWBT WORKFLOW',
    guideTitle: '素材仓库使用流程',
    guideMessage: '浏览器负责长期编辑队伍资料，OBS 控制台只接收本场需要的 A、B 两支队伍。',
    guideSteps: [
      { title: '整理队伍', body: '新建队伍，或把当前项目中的队伍保存到素材仓库并补齐阵容。' },
      { title: '选择对阵', body: '按直播左右顺序选择 A 队和 B 队，并打开检查确认素材状态。' },
      { title: '送入 OBS', body: '复制对阵包，在 OBS 控制台点击“粘贴对阵包”后开始本场导播。' }
    ],
    guideBackupTitle: '本地数据提醒',
    guideBackupNote: '素材保存在当前浏览器中。重要赛事开始前请导出备份，避免清理浏览器数据后丢失。',
    guideStart: '开始使用',
    teamAssets: '队伍资料',
    teams: '队伍',
    playersLabel: '选手',
    logos: '标志',
    suspectedDuplicates: '疑似重复',
    suspectedDuplicate: count => `疑似重复 ×${count}`,
    organizeDuplicates: '整理重复素材',
    duplicateCleanupTitle: '整理重复队伍',
    duplicateCleanupMessage: '为每组选择一个保留版本。其他版本只用于补齐缺失资料和不重复选手，确认后会删除重复记录。',
    duplicateCleanupGroups: count => `${count} 组重复队伍`,
    duplicateCleanupRemoved: count => `将移除 ${count} 条重复记录`,
    duplicateCleanupOmitted: count => `${count} 名选手因超过 7 人上限不会纳入`,
    keepVersion: '保留此版本',
    keeperSelected: '保留',
    exportBackupFirst: '先导出备份',
    confirmDuplicateMerge: '确认合并',
    duplicateMergeComplete: (groups, removed, omitted) => `已合并 ${groups} 组重复队伍，移除 ${removed} 条记录${omitted ? `，${omitted} 名超额选手未纳入` : ''}。`,
    matchPackage: '对阵包',
    localStorage: '本地存储',
    sideA: 'A 队',
    sideB: 'B 队',
    selectTeamA: '选择 A 队',
    selectTeamB: '选择 B 队',
    selectTeamAFirst: '请先选择 A 队',
    chooseMatchTeam: side => `选择 ${side}`,
    matchPickerSearch: '搜索队名、简称或选手',
    matchPickerNoResults: '没有匹配的队伍',
    currentSelection: '当前',
    library: '本地队伍',
    selected: '已选择',
    localOnly: '仅保存在当前浏览器',
    storage: '浏览器占用',
    librarySize: '素材库数据',
    saveState: '保存状态',
    savedLocally: '已保存到本机',
    localSavePending: '有未保存修改',
    localLibraryEmpty: '本地库为空',
    persistentStorage: '持久存储',
    persistenceEnabled: '已启用',
    persistenceUnavailable: '需备份',
    search: '搜索队伍或选手',
    empty: '素材库还是空的',
    emptyBody: '可以新建队伍，或把当前项目中的队伍保存进来。',
    railEmpty: '还没有队伍资料',
    railEmptyBody: '新建、导入或保存项目队伍后会显示在这里。',
    emptyKicker: '建立本地素材仓库',
    emptyStartTitle: '从第一支队伍开始',
    emptyStartBody: '手动创建队伍，保存当前项目中的队伍，或通过 CSV 和素材库备份批量导入。',
    noResults: '没有符合条件的队伍',
    players: count => `${count} 名选手`,
    updated: '更新',
    linked: '已载入项目',
    inspect: '队伍资料',
    teamName: '队伍名称',
    shortName: '简称',
    primaryColor: '队伍主色',
    logo: '队伍 Logo',
    logoPlaceholder: '图片地址或上传本地图片',
    visualAssets: '视觉素材',
    logoReady: 'Logo 已就绪',
    logoMissing: '未设置 Logo',
    logoSourceMissing: '尚未载入图片',
    logoSourceLocal: (format, size) => `本地 ${format || '图片'} / ${size}`,
    logoSourceRemote: '外部图片地址',
    logoUrl: '图片 URL',
    logoUrlPlaceholder: '粘贴图片 URL（可选）',
    localImageLoaded: '已载入本地图片',
    upload: '上传',
    clear: '清空',
    manager: '经理',
    coach: '教练',
    description: '备注',
    roster: '选手名单',
    addPlayer: '添加选手',
    playerName: '选手名',
    battleTag: '比赛 ID',
    role: '位置',
    playerAvatar: '选手头像',
    playerAvatarPlaceholder: '图片地址或上传本地图片',
    primaryHero: '常用英雄',
    portraitPosition: '人像横向位置',
    none: '不设置',
    avatarOptimized: (player, original, output) => `${player} 的头像已从 ${original} 优化为 ${output}，保存修改后写入素材库。`,
    avatarReady: (player, size) => `${player} 的头像已载入（${size}），保存修改后写入素材库。`,
    remove: '移除',
    save: '保存修改',
    delete: '删除素材',
    copyMatchPackage: '复制对阵包',
    copyMatchPackageAgain: '再次复制',
    selectionHint: '点击上方 A/B 选择器指定本场队伍',
    matchPackageStatus: count => count === 2 ? 'A/B 对阵已就绪' : count === 1 ? '继续选择 B 队' : '先选择 A 队',
    swapMatchSides: '互换 A / B',
    clearMatchSelection: '清空选择',
    maxSelected: '对阵包固定包含 A、B 两支队伍，请先取消一支已选队伍。',
    selectTwoTeams: '请按顺序选择 A、B 两支队伍。',
    matchPackageCopied: '对阵包已复制，可以粘贴到 OBS 导播台。',
    matchPackageNextStep: '下一步：在 OBS 控制台点击“粘贴对阵包”。',
    matchPackageCopyTitle: '复制对阵包文本',
    matchPackageCopyFallback: '无法直接写入剪贴板，请复制下面的完整文本。',
    matchPackageManualCopy: '请在文本框中按 Ctrl+A，再按 Ctrl+C 手动复制。',
    matchPackageDuplicateTeams: 'A 队和 B 队实际是同一支队伍，请重新选择。',
    matchPackageTooLarge: '对阵包超过 2 MB，请先压缩队伍 Logo 或选手头像后再复制。',
    healthCheck: count => count ? `检查 (${count})` : '检查',
    healthTitle: '对阵包检查',
    healthMessage: '提示项不会阻止复制；只有重复队伍、无效数据或超过 2 MB 时才会阻断。',
    healthStatus: '状态',
    healthPackageSize: '对阵包体积',
    healthChecks: '检查结果',
    healthReady: '可以使用',
    healthWarnings: count => `${count} 项提示`,
    healthBlocked: '需要处理',
    healthWarningSummary: count => `有 ${count} 项导播资料提示，可检查后继续复制。`,
    healthBlockedSummary: '存在阻断项，请打开检查并处理。',
    healthIssueCount: count => count ? `${count} 项` : '无问题',
    healthNoIssues: '两支队伍的导播资料完整，对阵包体积正常。',
    healthWarningLabel: '提示',
    healthBlockLabel: '阻断',
    healthMissingLogo: (side, team) => `${side} 队 ${team} 未设置队伍 Logo。`,
    healthShortRoster: (side, team, count) => `${side} 队 ${team} 只有 ${count} 名选手，建议至少配置 5 人。`,
    healthLargeLogo: (side, team, size) => `${side} 队 ${team} 的 Logo 为 ${size}，建议重新上传以自动优化。`,
    healthLargeAvatar: (side, player, size) => `${side} 队选手 ${player} 的头像为 ${size}，建议压缩。`,
    healthDuplicatePlayer: (side, player, count) => `${side} 队有 ${count} 条重复选手资料：${player}。`,
    healthLargePackage: size => `对阵包已达到 ${size}，接近 2 MB 上限。`,
    healthTooLarge: (size, limit) => `对阵包为 ${size}，已经超过 ${limit} 上限。`,
    healthDuplicateTeams: 'A 队和 B 队实际是同一支队伍，请重新选择。',
    healthInvalidPackage: '对阵包资料无效，请检查两支队伍。',
    matchPackageBuildFailed: '无法生成对阵包，请检查两支队伍的资料。',
    packageSize: (size, limit) => `${size} / ${limit}`,
    copyText: '复制文本',
    savedCurrent: count => `已将当前项目的 ${count} 支队伍保存到本地素材库。`,
    saveProjectPreviewTitle: '确认保存项目队伍',
    saveProjectPreviewMessage: '同名且缩写一致的队伍会覆盖原素材，其余队伍会新增。',
    confirmProjectSave: '确认保存',
    savedTeam: '队伍资料已保存。',
    shortNameRequired: '队伍简称不能为空。',
    unsavedTitle: '当前修改尚未保存',
    unsavedMessage: '离开当前队伍会丢失尚未保存的队伍、Logo 或选手修改。',
    keepEditing: '继续编辑',
    discardChanges: '放弃更改',
    importedBackup: count => `已从备份导入 ${count} 支队伍。`,
    importedBackupSummary: (additions, updates, duplicates) => `备份已合并：新增 ${additions}，覆盖 ${updates}，忽略重复 ${duplicates}。`,
    exportedBackup: count => `已导出包含 ${count} 支队伍的本地队伍库备份。`,
    backupTooLarge: '素材库备份超过 128 MB，请先压缩或移除大型 GIF、SVG 与头像素材。',
    importCsv: '导入 CSV',
    csvHelpTitle: '导入队伍 CSV',
    csvHelpMessage: '每行填写一名选手；同名且简称一致的行会归入同一支队伍。导入前可以先下载模板。',
    downloadCsvTemplate: '下载 CSV 模板',
    selectCsvFile: '选择 CSV 文件',
    csvRequiredColumns: '必需字段',
    csvRequiredColumnList: '队伍名称；队伍简称建议填写。',
    csvOptionalColumns: '可选字段',
    csvOptionalColumnList: 'Logo、主色、经理、教练、备注、选手名、比赛 ID、位置、头像、常用英雄、人像位置。',
    csvPreviewTitle: '确认合并 CSV',
    csvPreviewMessage: 'CSV 会新增或更新匹配队伍，不会删除素材库中的其他队伍。每队最多保留 7 名选手。',
    confirmCsvImport: '确认导入 CSV',
    csvSkippedRows: '跳过无队名行',
    csvOmittedPlayers: '超过 7 人',
    csvDuplicatePlayers: '重复选手',
    importedCsvSummary: (additions, updates, skipped, omitted, duplicates) => `CSV 已合并：新增 ${additions}，覆盖 ${updates}，跳过 ${skipped} 行、${omitted} 名超额选手和 ${duplicates} 条重复选手。`,
    invalidCsv: '无法识别这个 CSV，请检查表头、引号和队伍名称。',
    csvTooLarge: 'CSV 文件超过 2 MB，请拆分后再导入。',
    importCenter: '导入',
    importCenterTitle: '导入中心',
    importCenterMessage: '选择 JSON、CSV、TSV 或 TXT 文件，系统会自动识别 OWBT 项目、素材库备份、队伍资料和选手名单。也可以直接粘贴完整内容。',
    importCenterPlaceholder: '粘贴 OWBT 项目 JSON、素材库备份、队伍 CSV 或选手 CSV…',
    selectImportFile: '选择文件',
    analyzeImportText: '识别粘贴内容',
    pastedImportText: '粘贴的导入内容',
    downloadTeamCsvTemplate: '队伍 CSV 模板',
    teamCsvTemplateMeta: '新建或更新队伍与阵容',
    downloadPlayerCsvTemplate: '选手 CSV 模板',
    playerCsvTemplateMeta: '向已有队伍添加或更新选手',
    logoFolderToolMeta: '按队伍简称匹配图片文件名',
    brandingReviewTool: '整理简称与 Logo',
    brandingReviewToolMeta: '批量检查现有队伍视觉资料',
    teamCsv: '队伍 CSV',
    playerCsv: '选手 CSV',
    playerCsvPreviewTitle: '确认导入选手 CSV',
    playerCsvPreviewMessage: '选手只会加入已有队伍。优先按队伍简称匹配，比赛 ID 相同会更新现有选手，不会自动创建新队伍。',
    playerCsvAdded: '新增选手',
    playerCsvUpdated: '更新选手',
    playerCsvUnmatched: '队伍未匹配',
    playerCsvWarnings: '识别详情',
    playerCsvWarningSummary: (missing, ambiguous, duplicates, missingRoles, skipped, staff) => `未找到队伍 ${missing} / 简称冲突 ${ambiguous} / 重复行 ${duplicates} / 缺少位置 ${missingRoles} / 跳过空行 ${skipped} / 教练经理 ${staff}`,
    importedPlayerCsvSummary: (added, updated, missing, ambiguous, omitted, staff) => `选手 CSV 已导入：新增 ${added}，更新 ${updated}${staff ? `，更新教练或经理 ${staff}` : ''}${missing || ambiguous ? `，${missing + ambiguous} 行未匹配队伍` : ''}${omitted ? `，${omitted} 名选手超过 7 人上限` : ''}。`,
    invalidImportSource: '没有识别到可导入的 OWBT 项目、备份或 CSV 数据，请检查文件和表头是否完整。',
    invalidImportSourceDetails: (reason, headers) => `未能导入：${reason}${headers ? ` 当前识别到的首行是：${headers}。` : ''}`,
    importFailureReasons: {
      'project-invalid-json': '文件看起来不是完整 JSON，或使用了暂不支持的文本编码。',
      'project-no-team-data': 'JSON 可以读取，但其中没有找到 OWBT 队伍数组。',
      'project-no-valid-teams': '找到了队伍区域，但没有包含有效的队伍记录。',
      'library-unsupported-version': '这个队伍素材库备份来自不受支持的格式版本，当前版本只能导入 v1 备份。',
      'csv-no-data': '表格只有表头，没有可导入的数据行。',
      'csv-unclosed-quote': 'CSV 中存在未闭合的英文双引号。',
      'csv-missing-team-column': '没有找到队伍名称或队伍简称列。',
      'csv-missing-player-column': '选手表中没有找到选手名称或战网 ID 列。',
      'csv-no-valid-teams': '表格中没有包含有效队伍资料。'
    },
    importProjectTeams: '导入项目队伍',
    projectTeamImportTitle: '从 OWBT 项目导入队伍',
    projectTeamImportMessage: '选择现有 OWBT 项目 JSON，或粘贴完整项目文本。只提取队伍、选手和相关图片，不会导入比分、场景或比赛状态。',
    projectTeamImportPlaceholder: '在此粘贴 OWBT 导出的完整项目 JSON…',
    selectProjectJson: '选择 JSON 文件',
    analyzeProjectText: '识别项目文本',
    pastedProjectText: '粘贴的项目文本',
    projectTeamPreviewTitle: '确认导入项目队伍',
    projectTeamPreviewMessage: '同名且简称一致的队伍会更新，其余队伍会新增。素材库中的其他队伍不会被删除。',
    projectTeamSource: '识别来源',
    projectSourceType: '数据类型',
    projectSourceKinds: {
      project: 'OWBT 项目',
      'team-db': '旧队伍数据库',
      'library-backup': '素材库备份',
      generic: '兼容队伍数据'
    },
    chooseAnotherProjectSource: '重新选择',
    confirmProjectTeamImport: '确认导入队伍',
    invalidProjectTeamSource: '没有识别到可导入的 OWBT 队伍资料，请检查 JSON 是否完整。',
    projectTeamSourceTooLarge: '项目文件超过 24 MB，请先移除不需要的大型图片素材。',
    importedProjectTeamSummary: (additions, updates, players, omitted) => `项目队伍已导入：新增 ${additions}，覆盖 ${updates}，共 ${players} 名选手${omitted ? `，${omitted} 名超额选手未纳入` : ''}。`,
    importLogoFolder: '导入 Logo',
    brandingReviewTitle: '整理导入资料',
    brandingReviewMessage: '确认每支队伍的官方简称。简称不能为空且不能重复，确认后可直接载入以“简称”命名的 Logo 文件夹。',
    brandingReviewLater: '稍后整理',
    cancelImport: '取消导入',
    brandingReviewChooseLogos: '选择 Logo 文件夹',
    brandingReviewSave: '保存整理结果',
    brandingReviewSource: '资料来源',
    brandingReviewLogoReady: '已有 Logo',
    brandingReviewMissingLogo: '缺少 Logo',
    brandingReviewConflicts: '简称问题',
    brandingReviewBlocked: '请先处理简称问题',
    brandingReviewBlockedMeta: (missing, duplicates) => `简称为空 ${missing} 支 / 简称重复 ${duplicates} 支`,
    brandingReviewSaved: count => `已保存 ${count} 支队伍的简称与视觉资料。`,
    brandingLogoTitle: '确认简称与 Logo 匹配',
    brandingLogoMessage: '系统会按刚确认的简称优先匹配文件名，也兼容队伍全名、大小写、空格和常见标点差异。',
    saveBrandingAndLogos: '保存简称与 Logo',
    brandingReviewSavedWithLogos: (teams, logos, failed) => `已保存 ${teams} 支队伍资料并绑定 ${logos} 个 Logo${failed ? `，${failed} 个图片处理失败` : ''}。`,
    logoFolderTitle: '批量绑定队伍 Logo',
    logoFolderMessage: '图片文件名去掉扩展名后会优先匹配队伍简称，也兼容队伍全名、大小写、空格和常见标点差异。确认前不会修改素材库。',
    selectAnotherLogoFolder: '重新选择文件夹',
    confirmLogoFolderImport: '确认绑定 Logo',
    logoFolderImporting: '正在处理图片',
    logoFolderFiles: '文件总数',
    logoFolderMatched: '成功匹配',
    logoFolderOverwrite: '覆盖现有 Logo',
    logoFolderNeedsReview: '需要检查',
    logoFolderReplace: '替换',
    logoFolderAdd: '新增',
    logoFolderMore: count => `另有 ${count} 个匹配未展开`,
    logoFolderNoMatches: '没有找到与队伍简称一致的图片。请检查队伍简称和文件名。',
    logoFolderUnmatched: '未匹配简称',
    logoFolderAmbiguous: '队伍简称重复，未自动绑定',
    logoFolderDuplicates: '同简称存在多个文件，已选择更优格式',
    logoFolderRejected: '格式不支持或文件超过 3 MB',
    logoFolderAllFailed: '匹配到的 Logo 都无法读取，请检查图片文件。',
    importedLogoFolderSummary: (saved, failed) => `已为 ${saved} 支队伍更新 Logo${failed ? `，另有 ${failed} 个文件处理失败` : ''}。`,
    backupPreviewTitle: '确认合并素材库备份',
    backupPreviewMessage: '导入只新增或覆盖匹配队伍，不会删除当前素材库里的其他内容。',
    backupSource: '备份文件',
    confirmBackupImport: '确认合并导入',
    mergeAdd: '新增',
    mergeUpdate: '覆盖',
    mergeDuplicateInput: '备份内重复',
    mergeSummary: (additions, updates, duplicates) => `新增 ${additions} / 覆盖 ${updates} / 备份内重复 ${duplicates}`,
    mergeMore: count => `另有 ${count} 支队伍未展开`,
    duplicateTitle: '队伍简称已被使用',
    duplicateMessage: team => `这个简称已经属于“${team}”。请修改当前简称，或打开已有素材继续编辑。`,
    openExisting: '打开已有队伍',
    deletedTeam: '队伍素材已从本地资料库删除。',
    storageUnavailable: '当前浏览器无法使用 IndexedDB，队伍素材库不可用。',
    loadFailed: '读取本地队伍素材库失败。',
    saveFailed: '保存本地队伍素材失败，请检查浏览器可用空间。',
    invalidBackup: '无法识别这个 OWBT 队伍素材库备份。',
    unsupportedBackupVersion: '这个队伍素材库备份版本不受支持，当前版本只能导入 v1 备份。',
    invalidImage: '请选择 PNG、JPG、WebP、GIF 或 SVG 图片，单个文件不得超过 3 MB。',
    imageOptimized: (original, output) => `Logo 已从 ${original} 优化为 ${output}，保存修改后写入素材库。`,
    imageReady: size => `Logo 已载入（${size}），保存修改后写入素材库。`,
    loadMore: '继续加载',
    showingTeams: (shown, total) => `已显示 ${shown} / ${total} 支队伍`,
    cancel: '取消',
    deleteTitle: '删除本地素材',
    deleteMessage: team => `确定从本地素材库删除 ${team}？当前项目中的队伍资料会保留，但会解除与本地素材的关联。`,
    confirmDelete: '确认删除',
    close: '关闭',
    roleTank: '坦克',
    roleDamage: '输出',
    roleSupport: '支援'
  },
  en: {
    kicker: 'OWBT LOCAL DATA',
    title: 'Asset Library',
    subtitle: 'Keep reusable teams, rosters, and broadcast assets, then build a two-team package for the OBS console.',
    back: 'Back',
    saveCurrent: 'Save Project Teams',
    importBackup: 'Import Library Backup',
    exportBackup: 'Export Library Backup',
    createTeam: 'New Team',
    guideButton: 'Workflow',
    guideKicker: 'OWBT WORKFLOW',
    guideTitle: 'Asset Library Workflow',
    guideMessage: 'Use the browser to maintain teams long term. Send only the current Team A and Team B to the OBS console.',
    guideSteps: [
      { title: 'Prepare Teams', body: 'Create teams or save the current project teams, then complete each broadcast roster.' },
      { title: 'Select Matchup', body: 'Select Team A and Team B in broadcast order, then open Check to review the assets.' },
      { title: 'Send to OBS', body: 'Copy the match package and choose Paste Match Package in the OBS console.' }
    ],
    guideBackupTitle: 'Local Data Reminder',
    guideBackupNote: 'Assets stay in this browser. Export a backup before important events in case browser data is cleared.',
    guideStart: 'Start',
    teamAssets: 'Team Assets',
    teams: 'Teams',
    playersLabel: 'Players',
    logos: 'Logos',
    suspectedDuplicates: 'Possible Duplicates',
    suspectedDuplicate: count => `Possible duplicate ×${count}`,
    organizeDuplicates: 'Review Duplicates',
    duplicateCleanupTitle: 'Merge Duplicate Teams',
    duplicateCleanupMessage: 'Choose one version to keep in each group. Other versions only fill missing details and unique players; duplicate records are removed after confirmation.',
    duplicateCleanupGroups: count => `${count} duplicate groups`,
    duplicateCleanupRemoved: count => `${count} duplicate records will be removed`,
    duplicateCleanupOmitted: count => `${count} players exceed the seven-player limit and will not be included`,
    keepVersion: 'Keep This Version',
    keeperSelected: 'Keep',
    exportBackupFirst: 'Export Backup First',
    confirmDuplicateMerge: 'Merge Duplicates',
    duplicateMergeComplete: (groups, removed, omitted) => `Merged ${groups} duplicate groups and removed ${removed} records${omitted ? `; ${omitted} extra players were not included` : ''}.`,
    matchPackage: 'Match Package',
    localStorage: 'Local Storage',
    sideA: 'Team A',
    sideB: 'Team B',
    selectTeamA: 'Select Team A',
    selectTeamB: 'Select Team B',
    selectTeamAFirst: 'Select Team A first',
    chooseMatchTeam: side => `Select ${side}`,
    matchPickerSearch: 'Search team, short name, or player',
    matchPickerNoResults: 'No matching teams',
    currentSelection: 'Current',
    library: 'Local Teams',
    selected: 'Selected',
    localOnly: 'Stored only in this browser',
    storage: 'Browser Usage',
    librarySize: 'Library Data',
    saveState: 'Save Status',
    savedLocally: 'Saved Locally',
    localSavePending: 'Unsaved Changes',
    localLibraryEmpty: 'Local Library Empty',
    persistentStorage: 'Persistent Storage',
    persistenceEnabled: 'Enabled',
    persistenceUnavailable: 'Back Up',
    search: 'Search teams or players',
    empty: 'Your library is empty',
    emptyBody: 'Create a team or save the teams from the current project.',
    railEmpty: 'No team assets yet',
    railEmptyBody: 'Created, imported, and saved project teams will appear here.',
    emptyKicker: 'BUILD YOUR LOCAL LIBRARY',
    emptyStartTitle: 'Start With Your First Team',
    emptyStartBody: 'Create a team manually, save teams from the current project, or import them from CSV or a library backup.',
    noResults: 'No matching teams',
    players: count => `${count} players`,
    updated: 'Updated',
    linked: 'Loaded in project',
    inspect: 'Team Details',
    teamName: 'Team Name',
    shortName: 'Short Name',
    primaryColor: 'Primary Color',
    logo: 'Team Logo',
    logoPlaceholder: 'Image URL or upload a local image',
    visualAssets: 'Visual Assets',
    logoReady: 'Logo Ready',
    logoMissing: 'No Logo',
    logoSourceMissing: 'No image loaded',
    logoSourceLocal: (format, size) => `Local ${format || 'image'} / ${size}`,
    logoSourceRemote: 'External image URL',
    logoUrl: 'Image URL',
    logoUrlPlaceholder: 'Paste an image URL (optional)',
    localImageLoaded: 'Local image loaded',
    upload: 'Upload',
    clear: 'Clear',
    manager: 'Manager',
    coach: 'Coach',
    description: 'Notes',
    roster: 'Roster',
    addPlayer: 'Add Player',
    playerName: 'Player Name',
    battleTag: 'Battle ID',
    role: 'Role',
    playerAvatar: 'Player Portrait',
    playerAvatarPlaceholder: 'Image URL or upload a local image',
    primaryHero: 'Primary Hero',
    portraitPosition: 'Portrait Horizontal Position',
    none: 'None',
    avatarOptimized: (player, original, output) => `${player}'s portrait was optimized from ${original} to ${output}. Save changes to store it.`,
    avatarReady: (player, size) => `${player}'s portrait is ready (${size}). Save changes to store it.`,
    remove: 'Remove',
    save: 'Save Changes',
    delete: 'Delete Asset',
    copyMatchPackage: 'Copy Match Package',
    copyMatchPackageAgain: 'Copy Again',
    selectionHint: 'Use the Team A and Team B selectors above',
    matchPackageStatus: count => count === 2 ? 'Team A and Team B are ready' : count === 1 ? 'Now select Team B' : 'Select Team A first',
    swapMatchSides: 'Swap A / B',
    clearMatchSelection: 'Clear Selection',
    maxSelected: 'A match package contains exactly Team A and Team B. Deselect a team first.',
    selectTwoTeams: 'Select Team A and Team B in order.',
    matchPackageCopied: 'Match package copied. Paste it into the OBS console.',
    matchPackageNextStep: 'Next: choose Paste Match Package in the OBS console.',
    matchPackageCopyTitle: 'Copy Match Package Text',
    matchPackageCopyFallback: 'Clipboard access is unavailable. Copy the complete text below.',
    matchPackageManualCopy: 'Press Ctrl+A and then Ctrl+C in the text box to copy it manually.',
    matchPackageDuplicateTeams: 'Team A and Team B resolve to the same team. Choose two different teams.',
    matchPackageTooLarge: 'The match package exceeds 2 MB. Compress team logos or player portraits before copying.',
    healthCheck: count => count ? `Check (${count})` : 'Check',
    healthTitle: 'Match Package Check',
    healthMessage: 'Warnings do not prevent copying. Only duplicate teams, invalid data, or packages over 2 MB are blocked.',
    healthStatus: 'Status',
    healthPackageSize: 'Package Size',
    healthChecks: 'Checks',
    healthReady: 'Ready',
    healthWarnings: count => `${count} warnings`,
    healthBlocked: 'Action Required',
    healthWarningSummary: count => `${count} broadcast-data warnings. Review them or continue copying.`,
    healthBlockedSummary: 'A blocking issue must be resolved. Open Check for details.',
    healthIssueCount: count => count ? `${count} issues` : 'No issues',
    healthNoIssues: 'Both teams have complete broadcast data and the package size is healthy.',
    healthWarningLabel: 'Warning',
    healthBlockLabel: 'Blocked',
    healthMissingLogo: (side, team) => `Team ${side} (${team}) has no team logo.`,
    healthShortRoster: (side, team, count) => `Team ${side} (${team}) has ${count} players; at least five are recommended.`,
    healthLargeLogo: (side, team, size) => `Team ${side} (${team}) has a ${size} logo. Upload it again to optimize it.`,
    healthLargeAvatar: (side, player, size) => `Team ${side} player ${player} has a ${size} portrait. Compress it before use.`,
    healthDuplicatePlayer: (side, player, count) => `Team ${side} has ${count} duplicate player records for ${player}.`,
    healthLargePackage: size => `The match package is ${size}, close to the 2 MB limit.`,
    healthTooLarge: (size, limit) => `The match package is ${size}, above the ${limit} limit.`,
    healthDuplicateTeams: 'Team A and Team B resolve to the same team. Choose two different teams.',
    healthInvalidPackage: 'The match package data is invalid. Check both teams.',
    matchPackageBuildFailed: 'The match package could not be created. Check both team records.',
    packageSize: (size, limit) => `${size} / ${limit}`,
    copyText: 'Copy Text',
    savedCurrent: count => `Saved ${count} project teams to the local library.`,
    saveProjectPreviewTitle: 'Confirm Project Team Save',
    saveProjectPreviewMessage: 'Teams with the same name and short name will update existing assets. Other teams will be added.',
    confirmProjectSave: 'Save Teams',
    savedTeam: 'Team details saved.',
    shortNameRequired: 'The team short name cannot be empty.',
    unsavedTitle: 'Unsaved Changes',
    unsavedMessage: 'Leaving this team will discard unsaved team, logo, or player changes.',
    keepEditing: 'Keep Editing',
    discardChanges: 'Discard Changes',
    importedBackup: count => `Imported ${count} teams from the backup.`,
    importedBackupSummary: (additions, updates, duplicates) => `Backup merged: ${additions} added, ${updates} updated, ${duplicates} duplicate entries ignored.`,
    exportedBackup: count => `Exported a local library backup containing ${count} teams.`,
    backupTooLarge: 'The library backup is larger than 128 MB. Compress or remove large GIF, SVG, and avatar assets first.',
    importCsv: 'Import CSV',
    csvHelpTitle: 'Import Team CSV',
    csvHelpMessage: 'Use one player per row. Rows with the same team name and short name are grouped into one team. Download the template first if needed.',
    downloadCsvTemplate: 'Download CSV Template',
    selectCsvFile: 'Choose CSV File',
    csvRequiredColumns: 'Required',
    csvRequiredColumnList: 'Team name; a team short name is recommended.',
    csvOptionalColumns: 'Optional',
    csvOptionalColumnList: 'Logo, color, manager, coach, notes, player, Battle ID, role, portrait, primary hero, and portrait position.',
    csvPreviewTitle: 'Confirm CSV Merge',
    csvPreviewMessage: 'CSV adds or updates matching teams without deleting other library records. Each team keeps up to seven players.',
    confirmCsvImport: 'Import CSV',
    csvSkippedRows: 'Rows Missing Team',
    csvOmittedPlayers: 'Over Seven',
    csvDuplicatePlayers: 'Duplicate Players',
    importedCsvSummary: (additions, updates, skipped, omitted, duplicates) => `CSV merged: ${additions} added, ${updates} updated; skipped ${skipped} rows, ${omitted} extra players, and ${duplicates} duplicate players.`,
    invalidCsv: 'This CSV could not be read. Check the headers, quoted fields, and team names.',
    csvTooLarge: 'The CSV file is larger than 2 MB. Split it before importing.',
    importCenter: 'Import',
    importCenterTitle: 'Import Center',
    importCenterMessage: 'Choose a JSON, CSV, TSV, or TXT file. OWBT projects, library backups, team data, and player rosters are detected automatically. You can also paste the complete content.',
    importCenterPlaceholder: 'Paste an OWBT project JSON, library backup, team CSV, or player CSV…',
    selectImportFile: 'Choose File',
    analyzeImportText: 'Detect Pasted Data',
    pastedImportText: 'Pasted import data',
    downloadTeamCsvTemplate: 'Team CSV Template',
    teamCsvTemplateMeta: 'Create or update teams and rosters',
    downloadPlayerCsvTemplate: 'Player CSV Template',
    playerCsvTemplateMeta: 'Add or update players on existing teams',
    logoFolderToolMeta: 'Match image filenames to team short names',
    brandingReviewTool: 'Review Short Names and Logos',
    brandingReviewToolMeta: 'Check existing team identity assets in bulk',
    teamCsv: 'Team CSV',
    playerCsv: 'Player CSV',
    playerCsvPreviewTitle: 'Confirm Player CSV Import',
    playerCsvPreviewMessage: 'Players are assigned only to existing teams. Team short names are matched first, and an existing Battle ID updates that player. New teams are not created.',
    playerCsvAdded: 'Players Added',
    playerCsvUpdated: 'Players Updated',
    playerCsvUnmatched: 'Team Not Matched',
    playerCsvWarnings: 'Detection Details',
    playerCsvWarningSummary: (missing, ambiguous, duplicates, missingRoles, skipped, staff) => `Missing team ${missing} / ambiguous short name ${ambiguous} / duplicate rows ${duplicates} / missing roles ${missingRoles} / skipped rows ${skipped} / coach or manager ${staff}`,
    importedPlayerCsvSummary: (added, updated, missing, ambiguous, omitted, staff) => `Player CSV imported: ${added} added, ${updated} updated${staff ? `, ${staff} coach or manager fields updated` : ''}${missing || ambiguous ? `, ${missing + ambiguous} rows did not match a team` : ''}${omitted ? `, ${omitted} players exceeded the seven-player limit` : ''}.`,
    invalidImportSource: 'No supported OWBT project, backup, or CSV data was detected. Check that the file and headers are complete.',
    invalidImportSourceDetails: (reason, headers) => `Import failed: ${reason}${headers ? ` The first detected row was: ${headers}.` : ''}`,
    importFailureReasons: {
      'project-invalid-json': 'The file is not complete JSON or uses an unsupported text encoding.',
      'project-no-team-data': 'The JSON is readable, but no OWBT team array was found.',
      'project-no-valid-teams': 'A team section was found, but it contains no valid team records.',
      'library-unsupported-version': 'This Team Library backup uses an unsupported schema version. This release can import only v1 backups.',
      'csv-no-data': 'The table has a header but no importable data rows.',
      'csv-unclosed-quote': 'The CSV contains an unclosed double-quoted field.',
      'csv-missing-team-column': 'No team name or team short-name column was found.',
      'csv-missing-player-column': 'No player name or Battle ID column was found.',
      'csv-no-valid-teams': 'The table contains no valid team records.'
    },
    importProjectTeams: 'Import Project Teams',
    projectTeamImportTitle: 'Import Teams from an OWBT Project',
    projectTeamImportMessage: 'Choose an existing OWBT project JSON file or paste the full project text. Only teams, players, and their images are extracted; scores, scenes, and match state are ignored.',
    projectTeamImportPlaceholder: 'Paste a complete OWBT project JSON export here…',
    selectProjectJson: 'Choose JSON File',
    analyzeProjectText: 'Read Project Text',
    pastedProjectText: 'Pasted project text',
    projectTeamPreviewTitle: 'Confirm Project Team Import',
    projectTeamPreviewMessage: 'Teams with matching names and short names are updated; other teams are added. No other library teams are deleted.',
    projectTeamSource: 'Detected Source',
    projectSourceType: 'Data Type',
    projectSourceKinds: {
      project: 'OWBT Project',
      'team-db': 'Legacy Team Database',
      'library-backup': 'Library Backup',
      generic: 'Compatible Team Data'
    },
    chooseAnotherProjectSource: 'Choose Another',
    confirmProjectTeamImport: 'Import Teams',
    invalidProjectTeamSource: 'No importable OWBT team data was detected. Check that the JSON is complete.',
    projectTeamSourceTooLarge: 'The project file is larger than 24 MB. Remove unused large image assets first.',
    importedProjectTeamSummary: (additions, updates, players, omitted) => `Project teams imported: ${additions} added, ${updates} updated, ${players} players${omitted ? `, ${omitted} extra players omitted` : ''}.`,
    importLogoFolder: 'Logo Folder',
    brandingReviewTitle: 'Review Imported Team Assets',
    brandingReviewMessage: 'Confirm each official team short name. Short names cannot be empty or duplicated, then a folder of logos named by short name can be assigned directly.',
    brandingReviewLater: 'Review Later',
    cancelImport: 'Cancel Import',
    brandingReviewChooseLogos: 'Choose Logo Folder',
    brandingReviewSave: 'Save Review',
    brandingReviewSource: 'Source',
    brandingReviewLogoReady: 'Logos Ready',
    brandingReviewMissingLogo: 'Missing Logos',
    brandingReviewConflicts: 'Short-Name Issues',
    brandingReviewBlocked: 'Resolve the short-name issues first',
    brandingReviewBlockedMeta: (missing, duplicates) => `${missing} empty / ${duplicates} teams using duplicated short names`,
    brandingReviewSaved: count => `Saved short names and identity assets for ${count} teams.`,
    brandingLogoTitle: 'Confirm Short Names and Logo Matches',
    brandingLogoMessage: 'Filenames are matched against the reviewed short names first, with team-name, case, spacing, and common punctuation compatibility.',
    saveBrandingAndLogos: 'Save Short Names and Logos',
    brandingReviewSavedWithLogos: (teams, logos, failed) => `Saved ${teams} teams and assigned ${logos} logos${failed ? `; ${failed} images failed` : ''}.`,
    logoFolderTitle: 'Batch Assign Team Logos',
    logoFolderMessage: 'Image filenames are matched against team short names first, with team-name, case, spacing, and common punctuation compatibility. Nothing changes before confirmation.',
    selectAnotherLogoFolder: 'Choose Another Folder',
    confirmLogoFolderImport: 'Assign Logos',
    logoFolderImporting: 'Processing Images',
    logoFolderFiles: 'Files',
    logoFolderMatched: 'Matched',
    logoFolderOverwrite: 'Replace Existing',
    logoFolderNeedsReview: 'Needs Review',
    logoFolderReplace: 'Replace',
    logoFolderAdd: 'Add',
    logoFolderMore: count => `${count} more matches not shown`,
    logoFolderNoMatches: 'No image filename matches a team short name. Check the filenames and team records.',
    logoFolderUnmatched: 'No Matching Short Name',
    logoFolderAmbiguous: 'Duplicate Team Short Name',
    logoFolderDuplicates: 'Extra Files for the Same Short Name',
    logoFolderRejected: 'Unsupported or Larger Than 3 MB',
    logoFolderAllFailed: 'None of the matched logo files could be read. Check the image files.',
    importedLogoFolderSummary: (saved, failed) => `Updated logos for ${saved} teams${failed ? `; ${failed} files failed` : ''}.`,
    backupPreviewTitle: 'Confirm Library Backup Merge',
    backupPreviewMessage: 'Import adds or updates matching teams. It will not delete other teams already in the library.',
    backupSource: 'Backup File',
    confirmBackupImport: 'Merge Backup',
    mergeAdd: 'Add',
    mergeUpdate: 'Update',
    mergeDuplicateInput: 'Duplicates in Backup',
    mergeSummary: (additions, updates, duplicates) => `${additions} add / ${updates} update / ${duplicates} duplicate`,
    mergeMore: count => `${count} more teams not shown`,
    duplicateTitle: 'Team Short Name Already Used',
    duplicateMessage: team => `This short name already belongs to “${team}”. Change it or open the existing asset to continue editing.`,
    openExisting: 'Open Existing Team',
    deletedTeam: 'Team asset deleted from the local library.',
    storageUnavailable: 'IndexedDB is unavailable in this browser. The team library cannot be used.',
    loadFailed: 'Unable to read the local team library.',
    saveFailed: 'Unable to save team assets. Check available browser storage.',
    invalidBackup: 'This is not a valid OWBT team library backup.',
    unsupportedBackupVersion: 'This Team Library backup version is unsupported. This release can import only v1 backups.',
    invalidImage: 'Choose a PNG, JPG, WebP, GIF, or SVG image no larger than 3 MB.',
    imageOptimized: (original, output) => `Logo optimized from ${original} to ${output}. Save changes to store it.`,
    imageReady: size => `Logo ready (${size}). Save changes to store it.`,
    loadMore: 'Load More',
    showingTeams: (shown, total) => `Showing ${shown} of ${total} teams`,
    cancel: 'Cancel',
    deleteTitle: 'Delete Local Asset',
    deleteMessage: team => `Delete ${team} from the local library? The current project team will stay available, but its local-library link will be removed.`,
    confirmDelete: 'Delete',
    close: 'Close',
    roleTank: 'Tank',
    roleDamage: 'Damage',
    roleSupport: 'Support'
  }
}

export const getTeamLibraryCopy = language => COPY[language === 'en' ? 'en' : 'zh']
