import { getFriesCupCopyOverrides } from '../editions/friesCup/copy'

export const APP_COPY = {
  zh: {
    startupAria: 'OWBT 启动',
    bootText: '守望先锋社区导播系统',
    startupCreditLine: 'Designed by michaelsky5',
    startupReadyMeta: 'SYSTEM',
    communityLicense: '社区使用声明',
    startupNoticeLabel: 'Notice',
    noticeAcceptedShort: '已确认',
    noticeRequiredShort: '待确认',
    startupKicker: 'OWBT 开播配置',
    consoleTitle: '开播配置',
    enterConsole: '进入控制台',
    openingSettings: '开播前配置',
    language: '界面语言',
    eventName: '赛事名称',
    eventNameZh: '中文赛事名',
    eventNameEn: '英文赛事名',
    eventSubtitle: '赛事全称',
    eventLogo: '赛事 Logo 地址',
    clearLogo: '清空',
    openingTitle: '开场标题',
    openingSubtitle: '开场副标题',
    themePrimary: '主题主色',
    brandSubtitle: 'OW Community Edition',
    brandCredit: 'michaelsky5',
    scenes: '场景',
    program: '播出画面',
    programBadge: '播出',
    exportProject: '导出项目',
    importProject: '导入项目',
    importProjectConfirm: '导入项目会替换当前项目，现有内容会进入撤回栈。确认继续？',
    copyOverlayUrl: '复制 Overlay URL',
    resetProject: '重置项目',
    resetProjectConfirm: '重置项目会清空当前项目并回到默认数据，现有内容会进入撤回栈。',
    resetScore: '重置比分',
    swapSides: '一键换边',
    undoAction: '撤回',
    undoEmpty: '无撤回',
    project: '项目',
    eventNameField: '赛事名称',
    eventNameZhField: '中文赛事名',
    eventNameEnField: '英文赛事名',
    currentMatch: '当前比赛',
    data: '数据',
    dataCenter: '数据中心',
    workspaceDock: '工作区',
    setupDock: '开播设置',
    setupDockMeta: '开播 / 输出',
    settingsDock: '控制设置',
    settingsDockMeta: '控制台 / 快捷键',
    teams: '队伍',
    players: '选手',
    casters: '解说',
    scene: '场景',
    matchSetup: '比赛设置',
    stage: '赛事阶段',
    round: '地图场次',
    ft: '赛制',
    status: '状态',
    map: '当前地图',
    statusPending: '未开始',
    statusLive: '进行中',
    statusPause: '暂停',
    statusBreak: '中场休息',
    statusFinished: '已结束',
    teamSetup: '队伍设置',
    teamA: 'A 队',
    teamB: 'B 队',
    teamName: '队名',
    teamShortName: '缩写',
    teamPrimaryColor: '队伍主色',
    route: '路由',
    control: '控制台',
    output: '输出',
    quickActions: '快捷操作',
    realTimeStatus: '实时状态',
    operationLog: '操作日志',
    noLog: '暂无操作记录',
    preview: '预览',
    ok: '确定',
    importFailedTitle: '导入失败',
    invalidProjectFile: '无效的 OWBT 项目文件。',
    logPreview: scene => `预览 ${scene}`,
    logOpenSetup: '打开开播设置',
    logOpenToolbox: '打开工具箱',
    logOpenSettings: '打开控制设置',
    logAutoTake: scene => `自动切出 ${scene}`,
    logTake: scene => `切出 ${scene}`,
    logResetScore: '重置比分',
    logSwapTeams: '一键换边',
    logUndo: reason => `撤回 ${reason}`,
    logCopyOverlay: '复制 Overlay 地址',
    logResetProject: '重置项目',
    logImportProject: '导入项目',
    logImportFailed: '导入失败',
    logReasonEdit: '编辑',
    logReasonTake: '切出',
    logReasonSwapTeams: '换边',
    logReasonResetProject: '重置项目',
    logReasonImportProject: '导入项目',
    logReasonAction: '操作',
    consoleSettings: '控制台设置',
    settingControls: '控制台偏好',
    settingInterfaceLanguage: '界面语言',
    settingHotkeys: '快捷键',
    settingDisableInputs: '输入保护',
    settingConfirmDanger: '危险确认',
    settingStartWorkspace: '启动工作区',
    settingLogRows: '日志行数',
    settingSceneTransition: '场景转场',
    settingTransitionSpeed: '转场速度',
    settingTransitionLogo: '转场标识',
    settingOn: '开启',
    settingOff: '关闭',
    settingReset: '重置设置',
    settingHotkeyMap: '快捷键映射',
    settingGlobalPreferences: '全局偏好',
    settingTransitionPreferences: '转场偏好',
    transitionCut: '无转场',
    transitionNone: '无转场',
    transitionSimple: '简单转场',
    transitionScan: '品牌转场',
    transitionFast: '快速',
    transitionNormal: '标准',
    transitionSlow: '慢速',
    transitionLogoOff: '不显示',
    transitionLogoEvent: '赛事 Logo',
    transitionLogoOw: 'OWBT 标识',
    settingRuntime: '运行环境',
    settingWebRuntime: '网页端',
    settingWebRuntimeMeta: '本地保存 / Overlay / 静态导出',
    settingDesktopRuntime: '桌面端',
    settingDesktopRuntimeMeta: '本地路径 / 批量素材 / OBS Scene',
    settingDesktopOnly: '桌面端预留',
    settingAssetRoot: '素材根目录',
    settingExportDirectory: '导出目录',
    settingObsScenePath: 'OBS Scene 路径',
    settingDesktopLocked: '网页端锁定',
    settingDesktopMeta: '网页端不会直接读取本地文件系统；这些路径会在未来 Windows 桌面端开放。',
    startWorkspaceProduction: '导播台',
    startWorkspaceToolbox: '工具箱',
    startWorkspaceSettings: '控制设置',
    hotkeyTake: '切到输出',
    hotkeyUndo: '撤回操作',
    hotkeySwapTeams: '一键换边',
    hotkeyResetScore: '重置比分',
    hotkeyToolbox: '打开工具箱',
    hotkeySetup: '打开开播设置',
    hotkeySettings: '打开控制设置',
    hotkeyRecord: '录制',
    hotkeyRecording: '按键中',
    hotkeyReset: '重置',
    hotkeyConflict: '冲突',
    autosave: '自动保存',
    active: '启用',
    overlay: 'Overlay 地址',
    takeToProgram: '切到输出',
    alreadyOnProgram: '已在输出',
    previewScene: '预览场景',
    programScene: '输出场景',
    projectSummary: '项目信息',
    score: '比分',
    eventIdentity: '赛事信息',
    consoleStartup: '控制台启动',
    broadcastOutput: '播出输出',
    notes: '开播检查',
    projectName: '工作区名称',
    startupMotion: '启动动画',
    motionFull: '完整',
    motionReduced: '简化',
    overlayUrl: 'Overlay URL',
    overlayLanguage: 'Overlay 语言',
    overlayEnglish: '英文',
    overlayChinese: '中文',
    overlayChinesePending: '中文（待开发）',
    overlayLanguageLocked: '当前英文',
    overlayLanguagePending: '中文待开发',
    overlayLanguageLockedHint: '中文 Overlay 暂未开放，当前输出保持英文。',
    logoBackdrop: 'Logo 背景保护',
    logoBackdropAuto: '自动',
    logoBackdropDark: '深色',
    logoBackdropLight: '浅色',
    logoBackdropNone: '无背景',
    eventLogoPreview: 'Logo 预览',
    eventLogoReady: '已配置',
    eventLogoMissing: '未配置',
    eventLogoDefault: '默认标识',
    uploadLogo: '上传',
    invalidLogoFile: '请选择图片文件。',
    openOverlay: '打开 Overlay',
    resolution: '输出分辨率',
    transparentOverlay: '透明 Overlay',
    toolbox: '导播工具',
    toolboxMeta: '封面 / 对阵 / 赛果 / 导出',
    toolboxDockMeta: '图形 / 素材',
    copyUrl: '复制地址',
    resetBrand: '重置品牌',
    statusReady: '就绪',
    statusConfigured: '已配置',
    statusLocal: '本地',
    statusStandby: '待机',
    previewLabel: '预检',
    outputChecklist: 'OBS 输出清单',
    browserSource: '浏览器源',
    transparentBg: '透明背景',
    outputMode: '输出模式',
    versionNotes: '版本说明',
    versionNumber: 'V0.1',
    obsHintTitle: 'OBS 输出',
    obsHintBody: '浏览器源按所选输出分辨率设置（1080P / 4K），勾选透明背景，地址使用 Overlay URL。',
    changelogTitle: '更新说明',
    changelogBody: 'V0.1 已完成开播配置、导播台、多场景包装、数据中心和工具箱基础闭环。',
    updateNotesView: '查看更新',
    updateNotesBrief: '完成开播配置、导播台、多场景包装、数据中心和工具箱基础闭环。',
    updateNotesFull: [
      'V0.1 版本说明',
      '',
      '启动与基础设置',
      '- 新增开播配置入口，集中设置赛事名称、赛事 Logo、主题色、Overlay 地址、输出分辨率和透明背景。',
      '- 控制台支持中文 / English；Overlay 当前保持英文输出，中文 Overlay 暂未开放。',
      '',
      '导播控制台',
      '- 左侧场景选择、预览 / 输出双监看、切到输出、撤回、一键换边、重置比分和操作日志已接入。',
      '- 控制台设置支持快捷键、启动工作区、日志行数、输入保护、危险确认和场景转场偏好。',
      '',
      '场景与数据',
      '- 支持直播实况、地图设置、队伍阵容、解说席位、中场休息、媒体播放、流程包装和数据中心。',
      '- 数据中心包含比赛数据、选手数据、MVP、OCR 截图识别、指标板和地图数据导出。',
      '',
      '工具箱与素材',
      '- 工具箱支持直播封面、静态对阵图、静态赛果图、Scene 导出和素材管理。',
      '- 支持赛事 Logo、队伍 Logo、主办方 Logo、背景图、赞助 Logo / 视频素材上传。',
      '',
      '当前限制',
      '- Web 版以本地保存、Overlay 和静态导出为主；本地路径、批量素材和 OBS Scene 路径保留给未来 Windows 桌面版。'
    ].join('\n'),
    flowConfigTitle: '01 开播配置',
    flowConfigBody: '设置赛事名、赛事 Logo、主题色和播出输出。',
    flowRosterTitle: '02 录入资料',
    flowRosterBody: '进入导播台后录入队伍、选手和解说信息。',
    flowObsTitle: '03 接入 OBS',
    flowObsBody: '复制 Overlay URL，并按输出分辨率建立浏览器源。',
    flowLiveTitle: '04 开始导播',
    flowLiveBody: '用场景选择、预览切出和快捷操作完成直播。',
    guideTitle: '开播流程',
    guideBody: '确认赛事信息、Logo 和主题色，再复制 Overlay 地址进入导播台。',
    usageNoticeTitle: '使用声明',
    usageNoticeBody: 'OWBT 是 michaelsky5 制作的免费社区导播工具，不是 Blizzard 或 Overwatch 官方产品，也不代表任何官方授权或背书。',
    usageNoticeBodySecondary: '你可以将 OWBT 用于社区赛事与非商业直播；赛事 Logo、队伍 Logo、赞助信息、游戏画面和其他第三方素材的授权与合规由使用者自行负责。',
    usageNoticeBadge: '免费社区使用',
    usageNoticePanelLabel: '使用声明',
    usageRuleFree: '免费使用',
    usageRuleFreeMeta: '社区赛事',
    usageRuleFreeDetail: '社区赛事与非商业直播可免费使用，可按赛事需求配置项目内容。',
    usageRuleCredit: '作者署名',
    usageRuleCreditMeta: '保留署名',
    usageRuleCreditDetail: '默认保留作者署名；如需移除或调整，请先获得作者授权。',
    usageRuleNoProfit: '禁止转售',
    usageRuleNoProfitMeta: '非商业分发',
    usageRuleNoProfitDetail: '不得转售、白标改包、付费授权，或作为付费服务分发。',
    usageRuleAssets: '素材责任',
    usageRuleAssetsMeta: '第三方素材',
    usageRuleAssetsDetail: '使用赛事、队伍、赞助或游戏画面等素材前，请自行确认授权与合规。',
    usageNoticeAccept: '同意并进入',
    usageNoticeRequired: '首次进入需要确认使用声明',
    usageNoticeAccepted: '使用声明已确认',
    usageNoticeView: '查看声明',
    usageNoticeClose: '关闭',
    enterSetup: '进入开播设置',
    cancel: '取消',
    zhShort: '中文',
    enShort: 'English'
  },
  en: {
    startupAria: 'OWBT startup',
    bootText: 'OW Community Broadcast System',
    startupCreditLine: 'Designed by michaelsky5',
    startupReadyMeta: 'System',
    communityLicense: 'Community Usage Notice',
    startupNoticeLabel: 'Notice',
    noticeAcceptedShort: 'Accepted',
    noticeRequiredShort: 'Required',
    startupKicker: 'OWBT Startup',
    consoleTitle: 'Startup Setup',
    enterConsole: 'Enter Console',
    openingSettings: 'Opening Settings',
    language: 'Interface Language',
    eventName: 'Event Name',
    eventNameZh: 'Chinese Event Name',
    eventNameEn: 'English Event Name',
    eventSubtitle: 'Event Full Name',
    eventLogo: 'Event Logo URL',
    clearLogo: 'Clear',
    openingTitle: 'Opening Title',
    openingSubtitle: 'Opening Subtitle',
    themePrimary: 'Theme Primary',
    brandSubtitle: 'OW Community Edition',
    brandCredit: 'michaelsky5',
    scenes: 'Scene Selector',
    program: 'Program',
    programBadge: 'PROGRAM',
    exportProject: 'Export Project',
    importProject: 'Import Project',
    importProjectConfirm: 'Import Project will replace the current project. The current state will be kept in the undo stack. Continue?',
    copyOverlayUrl: 'Copy Overlay URL',
    resetProject: 'Reset Project',
    resetProjectConfirm: 'Reset Project will clear the current project and restore default data. The current state will be kept in the undo stack.',
    resetScore: 'Reset Score',
    swapSides: 'Swap Sides',
    undoAction: 'Undo',
    undoEmpty: 'NO UNDO',
    project: 'Project',
    eventNameField: 'Event Name',
    eventNameZhField: 'Chinese Event Name',
    eventNameEnField: 'English Event Name',
    currentMatch: 'Current Match',
    data: 'Data',
    dataCenter: 'Data Center',
    workspaceDock: 'Workspace',
    setupDock: 'Setup',
    setupDockMeta: 'Startup / Output',
    settingsDock: 'Settings',
    settingsDockMeta: 'Console / Hotkeys',
    teams: 'Teams',
    players: 'Players',
    casters: 'Casters',
    scene: 'Scene',
    matchSetup: 'Match Setup',
    stage: 'Stage',
    round: 'Round Label',
    ft: 'Format',
    status: 'Status',
    map: 'Current Map',
    statusPending: 'Pending',
    statusLive: 'Live',
    statusPause: 'Paused',
    statusBreak: 'Break',
    statusFinished: 'Finished',
    teamSetup: 'Team Setup',
    teamA: 'Team A',
    teamB: 'Team B',
    teamName: 'Team Name',
    teamShortName: 'Short Name',
    teamPrimaryColor: 'Team Primary',
    route: 'Route',
    control: 'Control',
    output: 'Output',
    quickActions: 'Quick Actions',
    realTimeStatus: 'Real-Time Status',
    operationLog: 'Operation Log',
    noLog: 'No operation yet',
    preview: 'Preview',
    ok: 'OK',
    importFailedTitle: 'Import Failed',
    invalidProjectFile: 'Invalid OWBT project file.',
    logPreview: scene => `PREVIEW ${scene}`,
    logOpenSetup: 'OPEN SETUP',
    logOpenToolbox: 'OPEN TOOLBOX',
    logOpenSettings: 'OPEN SETTINGS',
    logAutoTake: scene => `AUTO TAKE ${scene}`,
    logTake: scene => `TAKE ${scene}`,
    logResetScore: 'RESET SCORE',
    logSwapTeams: 'SWAP TEAMS',
    logUndo: reason => `UNDO ${reason}`,
    logCopyOverlay: 'COPY OVERLAY URL',
    logResetProject: 'RESET PROJECT',
    logImportProject: 'IMPORT PROJECT',
    logImportFailed: 'IMPORT FAILED',
    logReasonEdit: 'EDIT',
    logReasonTake: 'TAKE',
    logReasonSwapTeams: 'SWAP TEAMS',
    logReasonResetProject: 'RESET PROJECT',
    logReasonImportProject: 'IMPORT PROJECT',
    logReasonAction: 'ACTION',
    consoleSettings: 'Console Settings',
    settingControls: 'Console Control',
    settingInterfaceLanguage: 'Interface Language',
    settingHotkeys: 'Hotkeys',
    settingDisableInputs: 'Input Guard',
    settingConfirmDanger: 'Confirm Risk',
    settingStartWorkspace: 'Start Workspace',
    settingLogRows: 'Log Rows',
    settingSceneTransition: 'Scene Transition',
    settingTransitionSpeed: 'Transition Speed',
    settingTransitionLogo: 'Transition Logo',
    settingOn: 'ON',
    settingOff: 'OFF',
    settingReset: 'Reset Settings',
    settingHotkeyMap: 'Hotkey Map',
    settingGlobalPreferences: 'Global Preferences',
    settingTransitionPreferences: 'Transition Preferences',
    transitionCut: 'No Transition',
    transitionNone: 'No Transition',
    transitionSimple: 'Simple Wipe',
    transitionScan: 'Brand Stinger',
    transitionFast: 'Fast',
    transitionNormal: 'Normal',
    transitionSlow: 'Slow',
    transitionLogoOff: 'Off',
    transitionLogoEvent: 'Event Logo',
    transitionLogoOw: 'OWBT Mark',
    settingRuntime: 'Runtime',
    settingWebRuntime: 'Web App',
    settingWebRuntimeMeta: 'Local save / Overlay / Static export',
    settingDesktopRuntime: 'Desktop App',
    settingDesktopRuntimeMeta: 'Local paths / Bulk assets / OBS Scene',
    settingDesktopOnly: 'Desktop Reserved',
    settingAssetRoot: 'Asset Root',
    settingExportDirectory: 'Export Directory',
    settingObsScenePath: 'OBS Scene Path',
    settingDesktopLocked: 'WEB LOCKED',
    settingDesktopMeta: 'These local paths are reserved for the future Windows desktop app. The web app will not read the local file system directly.',
    startWorkspaceProduction: 'Production',
    startWorkspaceToolbox: 'Toolbox',
    startWorkspaceSettings: 'Settings',
    hotkeyTake: 'Take Preview',
    hotkeyUndo: 'Undo Action',
    hotkeySwapTeams: 'Swap Teams',
    hotkeyResetScore: 'Reset Score',
    hotkeyToolbox: 'Open Toolbox',
    hotkeySetup: 'Open Setup',
    hotkeySettings: 'Open Settings',
    hotkeyRecord: 'Record',
    hotkeyRecording: 'Recording',
    hotkeyReset: 'Reset',
    hotkeyConflict: 'Conflict',
    autosave: 'Autosave',
    active: 'Active',
    overlay: 'Overlay URL',
    takeToProgram: 'Take To Program',
    alreadyOnProgram: 'Already On Program',
    previewScene: 'Preview Scene',
    programScene: 'Program Scene',
    projectSummary: 'Project Summary',
    score: 'Score',
    eventIdentity: 'Event Identity',
    consoleStartup: 'Console Startup',
    broadcastOutput: 'Broadcast Output',
    notes: 'Preflight Check',
    projectName: 'Workspace Name',
    startupMotion: 'Splash Animation',
    motionFull: 'Full',
    motionReduced: 'Reduced',
    overlayUrl: 'Overlay URL',
    overlayLanguage: 'Overlay Language',
    overlayEnglish: 'English',
    overlayChinese: '中文',
    overlayChinesePending: 'Chinese (Coming Soon)',
    overlayLanguageLocked: 'English Active',
    overlayLanguagePending: 'Chinese Pending',
    overlayLanguageLockedHint: 'Chinese overlay output is not available yet. Current output stays in English.',
    logoBackdrop: 'Logo Backdrop',
    logoBackdropAuto: 'Auto',
    logoBackdropDark: 'Dark',
    logoBackdropLight: 'Light',
    logoBackdropNone: 'None',
    eventLogoPreview: 'Logo Preview',
    eventLogoReady: 'Configured',
    eventLogoMissing: 'Missing',
    eventLogoDefault: 'Default Mark',
    uploadLogo: 'Upload',
    invalidLogoFile: 'Select an image file.',
    openOverlay: 'Open Overlay',
    resolution: 'Output Resolution',
    transparentOverlay: 'Transparent Overlay',
    toolbox: 'Toolbox',
    toolboxMeta: 'COVER / MATCHUP / RESULT / EXPORT',
    toolboxDockMeta: 'Graphics / Assets',
    copyUrl: 'Copy URL',
    resetBrand: 'Reset Brand',
    statusReady: 'READY',
    statusConfigured: 'CONFIGURED',
    statusLocal: 'LOCAL',
    statusStandby: 'STANDBY',
    previewLabel: 'Preflight',
    outputChecklist: 'OBS Output Checklist',
    browserSource: 'Browser Source',
    transparentBg: 'Transparent BG',
    outputMode: 'Output Mode',
    versionNotes: 'Version Notes',
    versionNumber: 'V0.1',
    obsHintTitle: 'OBS Output',
    obsHintBody: 'Set the Browser Source to the selected output resolution (1080P / 4K), enable transparent background, and use the Overlay URL.',
    changelogTitle: 'Update Notes',
    changelogBody: 'V0.1 completes the first loop for startup setup, production console, scene packages, data center, and toolbox.',
    updateNotesView: 'View Updates',
    updateNotesBrief: 'Startup setup, production console, scene packages, data center, and toolbox are now connected.',
    updateNotesFull: [
      'V0.1 Release Notes',
      '',
      'Startup And Basics',
      '- Added startup setup for event names, event logo, theme color, Overlay URL, output resolution, and transparent background.',
      '- Console language supports Chinese / English; overlay output currently stays in English.',
      '',
      'Production Console',
      '- Scene selector, preview / program monitors, take, undo, swap sides, reset score, and operation log are connected.',
      '- Console settings include hotkeys, start workspace, log rows, input guard, danger confirmation, and scene transition preferences.',
      '',
      'Scenes And Data',
      '- Supports Live, Map Setup, Team Roster, Caster Desk, Break, Media, Show Flow, and Data Center scenes.',
      '- Data Center includes match stats, player data, MVP, OCR screenshot capture, metric board, and map data export.',
      '',
      'Toolbox And Assets',
      '- Toolbox supports stream cover, static matchup, static result, Scene export, and asset management.',
      '- Event logos, team logos, organizer logos, backgrounds, sponsor logos, and sponsor video assets can be uploaded.',
      '',
      'Current Limits',
      '- Web version focuses on local save, Overlay, and static export; local paths, bulk assets, and OBS Scene paths are reserved for the future Windows desktop app.'
    ].join('\n'),
    flowConfigTitle: '01 Startup Setup',
    flowConfigBody: 'Set event names, event logo, theme color, and broadcast output.',
    flowRosterTitle: '02 Enter Data',
    flowRosterBody: 'Enter teams, players, and casters after opening the console.',
    flowObsTitle: '03 Connect OBS',
    flowObsBody: 'Copy the Overlay URL and create a Browser Source at the selected output size.',
    flowLiveTitle: '04 Go Live',
    flowLiveBody: 'Use scene selection, preview/take, and quick actions for the broadcast.',
    guideTitle: 'Startup Flow',
    guideBody: 'Confirm event identity, logo, and theme color, then copy the Overlay URL and enter production.',
    usageNoticeTitle: 'Usage Notice',
    usageNoticeBody: 'OWBT is a free community broadcast tool made by michaelsky5. It is not an official Blizzard or Overwatch product and does not imply official authorization or endorsement.',
    usageNoticeBodySecondary: 'You may use OWBT for community tournaments and non-commercial broadcasts; permission and compliance for event logos, team logos, sponsor marks, gameplay footage, and other third-party assets are the user\'s responsibility.',
    usageNoticeBadge: 'Free Community Use',
    usageNoticePanelLabel: 'Usage Notice',
    usageRuleFree: 'Free Use',
    usageRuleFreeMeta: 'Community Events',
    usageRuleFreeDetail: 'Free for community and non-commercial broadcasts; configure project content for each event.',
    usageRuleCredit: 'Creator Credit',
    usageRuleCreditMeta: 'Keep Credit',
    usageRuleCreditDetail: 'Keep creator credit by default; request permission before removing or changing it.',
    usageRuleNoProfit: 'No Resale',
    usageRuleNoProfitMeta: 'Non-commercial',
    usageRuleNoProfitDetail: 'Do not resell, white-label, sublicense, or distribute it as a paid service.',
    usageRuleAssets: 'Asset Responsibility',
    usageRuleAssetsMeta: 'Third-party Assets',
    usageRuleAssetsDetail: 'Confirm permission and compliance before using event, team, sponsor, or gameplay assets.',
    usageNoticeAccept: 'Agree and Enter',
    usageNoticeRequired: 'Usage notice required before setup',
    usageNoticeAccepted: 'Usage notice accepted',
    usageNoticeView: 'View Notice',
    usageNoticeClose: 'Close',
    enterSetup: 'Enter Setup',
    cancel: 'Cancel',
    zhShort: '中文',
    enShort: 'English'
  }
}

export const getAppLanguage = (project, overrideLanguage = '') => {
  const language = overrideLanguage || project?.event?.language
  return language === 'zh' ? 'zh' : 'en'
}

export const getAppCopy = (project, overrideLanguage = '') => {
  const language = getAppLanguage(project, overrideLanguage)
  return {
    ...APP_COPY[language],
    ...getFriesCupCopyOverrides(language)
  }
}
