const TOOLBOX_COPY = {
  zh: {
    title: '工具箱',
    kicker: 'OWBT 工具箱',
    modes: {
      cover: { label: '直播封面', shortLabel: '封面', meta: '直播封面导出' },
      matchup: { label: '静态对阵图', shortLabel: '对阵', meta: '对阵卡导出' },
      result: { label: '静态赛果图', shortLabel: '赛果', meta: '赛果卡导出' },
      assets: { label: '素材管理', shortLabel: '素材', meta: '队标 / 赞助' },
      'export-scene': { label: 'Scene 导出', shortLabel: '场景', meta: '场景 PNG' }
    },
    sceneGroups: {
      core: '核心场景',
      'show-flow': '流程包装',
      break: '中场控制',
      media: '媒体播放',
      data: '数据中心'
    },
    exportManifest: '导出清单',
    exportFileName: '文件名',
    exportTarget: '导出目标',
    aspectRatio: '画幅比例',
    dataMode: '数据模式',
    exportSettings: '导出设置',
    dataSource: '数据来源',
    currentMatchData: '当前比赛数据',
    snapshotData: '数据快照',
    outputSize: '输出尺寸',
    fileType: '文件格式',
    customSize: '自定义尺寸',
    manualSize: '手动输入',
    width: '宽度',
    height: '高度',
    toolSettings: '工具设置',
    contentGroup: '内容',
    displayGroup: '显示',
    scoreGroup: '比分',
    fieldTitle: '标题',
    fieldSubtitle: '副标题',
    fieldEyebrow: '标签',
    labelQuick: '标签快捷',
    fieldStage: '阶段',
    fieldTime: '时间',
    fieldWinner: '胜者',
    fieldScoreA: 'A 队比分',
    fieldScoreB: 'B 队比分',
    titleQuick: '标题快捷',
    stageQuick: '阶段快捷',
    timeQuick: '时间快捷',
    displayOptions: '显示选项',
    clearTime: '清空时间',
    winnerQuick: '胜者快捷',
    autoWinner: '自动判断',
    draw: '平局',
    scoreSource: '比分来源',
    useCurrentScore: '使用当前比分',
    manualScore: '手动比分',
    fieldMvp: 'MVP',
    fieldNote: '备注',
    showTeams: '显示队伍',
    showDetails: '显示详情',
    showTime: '显示时间',
    showFt: '显示赛制',
    showMap: '显示地图',
    titleSize: '标题字号',
    subtitleSize: '副标题字号',
    teamShortSize: '队伍缩写字号',
    eventLogoBg: '赛事 Logo 背景',
    teamLogoBg: '队伍 Logo 背景',
    teamA: 'A 队',
    teamB: 'B 队',
    currentValue: '当前',
    swapTeams: '换边',
    auto: '自动',
    targetScene: '目标场景',
    exportPng: '导出 PNG',
    exporting: '导出中',
    exportReady: '可导出',
    exportFailed: '导出失败',
    exportHint: '跨域图片可能导致导出失败；上传图片或同源素材最稳定。',
    recentExports: '最近导出',
    noRecentExports: '暂无导出记录',
    status: '状态',
    draft: '草稿',
    selectedTool: '当前工具',
    useCurrent: '使用当前比赛数据',
    snapshotCurrent: '快照当前数据',
    snapshotMode: '快照数据',
    savedToProject: '已保存到项目',
    noSnapshot: '还没有快照',
    exportSceneHint: '下一步会选择要导出的播出场景。',
    event: '赛事',
    match: '比赛',
    score: '比分',
    format: '赛制',
    map: '地图',
    winner: '胜者',
    series: '系列',
    programScene: '播出场景',
    assetSettings: '素材配置',
    eventPackage: '赛事素材',
    matchAssets: '比赛队伍素材',
    sponsorPackage: '赞助素材',
    assetSummary: '素材状态',
    eventLogo: '赛事 Logo',
    organizerLogo: '主办方 Logo',
    backgroundImage: '背景图',
    teamALogo: 'A 队 Logo',
    teamBLogo: 'B 队 Logo',
    teamAColor: 'A 队颜色',
    teamBColor: 'B 队颜色',
    teamLogo: '队伍 Logo',
    teamColor: '队伍颜色',
    sponsorTicker: '赞助滚动条',
    sponsorVideo: '赞助视频',
    sponsorName: '赞助商名称',
    sponsorLogo: '赞助商 Logo',
    addSponsor: '添加赞助商',
    remove: '移除',
    enabled: '启用',
    sourcePath: '路径',
    action: '操作',
    enabledOn: '开启',
    enabledOff: '关闭',
    expand: '展开',
    collapse: '收起',
    advancedStudio: '高级素材库',
    teamAssetLibrary: '所有队伍素材库',
    searchTeams: '搜索队伍',
    searchTeamsPlaceholder: '队伍 / 缩写 / ID',
    allTeams: '全部',
    missingLogo: '缺 Logo',
    hasLogo: '有 Logo',
    currentMatch: '当前对阵',
    selectedTeam: '选中队伍',
    noTeamSelected: '选择一支队伍编辑素材',
    teamCount: '队伍数',
    currentMatchAssets: '当前对阵素材',
    basicAssets: '基础素材',
    loadFile: '载入',
    clear: '清空',
    applyToMedia: '应用到媒体播放',
    team: '队伍',
    logo: 'Logo',
    color: '颜色',
    sponsorDefaultName: index => `赞助商 ${index + 1}`,
    sponsorTickerPlaceholder: '由社区合作伙伴支持',
    sponsorTickerFallback: '赞助滚动条',
    ready: '已配置',
    empty: '未配置',
    logos: 'Logo',
    video: '视频'
  },
  en: {
    title: 'Toolbox',
    kicker: 'OWBT TOOLBOX',
    modes: {
      cover: { label: 'Cover Maker', shortLabel: 'Cover', meta: 'Stream cover' },
      matchup: { label: 'Static Matchup', shortLabel: 'Matchup', meta: 'Versus card export' },
      result: { label: 'Static Result', shortLabel: 'Result', meta: 'Final card export' },
      assets: { label: 'Assets', shortLabel: 'Assets', meta: 'Logos / sponsor' },
      'export-scene': { label: 'Export Scene', shortLabel: 'Scene', meta: 'Scene PNG' }
    },
    sceneGroups: {
      core: 'Core',
      'show-flow': 'Show Flow',
      break: 'Break',
      media: 'Media',
      data: 'Data'
    },
    exportManifest: 'Export Manifest',
    exportFileName: 'Filename',
    exportTarget: 'Export Target',
    aspectRatio: 'Aspect Ratio',
    dataMode: 'Data Mode',
    exportSettings: 'Export Settings',
    dataSource: 'Data Source',
    currentMatchData: 'Current Match Data',
    snapshotData: 'Snapshot Data',
    outputSize: 'Output Size',
    fileType: 'File Type',
    customSize: 'Custom Size',
    manualSize: 'Manual',
    width: 'Width',
    height: 'Height',
    toolSettings: 'Tool Settings',
    contentGroup: 'Content',
    displayGroup: 'Display',
    scoreGroup: 'Score',
    fieldTitle: 'Title',
    fieldSubtitle: 'Subtitle',
    fieldEyebrow: 'Label',
    labelQuick: 'Label Quick Pick',
    fieldStage: 'Stage',
    fieldTime: 'Time',
    fieldWinner: 'Winner',
    fieldScoreA: 'Team A Score',
    fieldScoreB: 'Team B Score',
    titleQuick: 'Title Quick Pick',
    stageQuick: 'Stage Quick Pick',
    timeQuick: 'Time Quick Pick',
    displayOptions: 'Display Options',
    clearTime: 'Clear Time',
    winnerQuick: 'Winner Quick Pick',
    autoWinner: 'Auto Winner',
    draw: 'Draw',
    scoreSource: 'Score Source',
    useCurrentScore: 'Use Current Score',
    manualScore: 'Manual Score',
    fieldMvp: 'MVP',
    fieldNote: 'Note',
    showTeams: 'Show Teams',
    showDetails: 'Show Details',
    showTime: 'Show Time',
    showFt: 'Show Format',
    showMap: 'Show Map',
    titleSize: 'Title Size',
    subtitleSize: 'Subtitle Size',
    teamShortSize: 'Team Short Size',
    eventLogoBg: 'Event Logo BG',
    teamLogoBg: 'Team Logo BG',
    teamA: 'Team A',
    teamB: 'Team B',
    currentValue: 'Current',
    swapTeams: 'Swap',
    auto: 'Auto',
    targetScene: 'Target Scene',
    exportPng: 'Export PNG',
    exporting: 'Exporting',
    exportReady: 'Ready',
    exportFailed: 'Export Failed',
    exportHint: 'Cross-origin images may fail to export; uploaded or same-origin assets are safest.',
    recentExports: 'Recent Exports',
    noRecentExports: 'No exports yet',
    status: 'Status',
    draft: 'DRAFT',
    selectedTool: 'Selected Tool',
    useCurrent: 'Use Current Match Data',
    snapshotCurrent: 'Snapshot Current Data',
    snapshotMode: 'Snapshot Data',
    savedToProject: 'Saved to project',
    noSnapshot: 'No snapshot yet',
    exportSceneHint: 'Export Scene will use the selected broadcast scene in the next step.',
    event: 'Event',
    match: 'Match',
    score: 'Score',
    format: 'Format',
    map: 'Map',
    winner: 'Winner',
    series: 'Series',
    programScene: 'Program Scene',
    assetSettings: 'Asset Settings',
    eventPackage: 'Event Assets',
    matchAssets: 'Match Team Assets',
    sponsorPackage: 'Sponsor Assets',
    assetSummary: 'Asset Status',
    eventLogo: 'Event Logo',
    organizerLogo: 'Organizer Logo',
    backgroundImage: 'Background Image',
    teamALogo: 'Team A Logo',
    teamBLogo: 'Team B Logo',
    teamAColor: 'Team A Color',
    teamBColor: 'Team B Color',
    teamLogo: 'Team Logo',
    teamColor: 'Team Color',
    sponsorTicker: 'Sponsor Ticker',
    sponsorVideo: 'Sponsor Video',
    sponsorName: 'Sponsor Name',
    sponsorLogo: 'Sponsor Logo',
    addSponsor: 'Add Sponsor',
    remove: 'Remove',
    enabled: 'Enabled',
    sourcePath: 'Path',
    action: 'Action',
    enabledOn: 'ON',
    enabledOff: 'OFF',
    expand: 'Expand',
    collapse: 'Collapse',
    advancedStudio: 'Advanced / Studio',
    teamAssetLibrary: 'Team Asset Library',
    searchTeams: 'Search Teams',
    allTeams: 'All',
    missingLogo: 'Missing Logo',
    hasLogo: 'Has Logo',
    currentMatch: 'Current Match',
    selectedTeam: 'Selected Team',
    noTeamSelected: 'Select a team to edit assets',
    teamCount: 'Teams',
    currentMatchAssets: 'Current Match Assets',
    basicAssets: 'Basic Assets',
    loadFile: 'Load',
    clear: 'Clear',
    applyToMedia: 'Apply to Media',
    ready: 'Ready',
    empty: 'Empty',
    logos: 'Logos',
    video: 'Video'
  }
}

export const getToolboxCopy = language => TOOLBOX_COPY[language] || TOOLBOX_COPY.en

export const getToolboxModeDisplay = (text, mode) => {
  const modeCopy = text.modes?.[mode.id] || {}
  const label = modeCopy.label || mode.label || mode.id

  return {
    label,
    shortLabel: modeCopy.shortLabel || mode.shortLabel || label,
    meta: modeCopy.meta || mode.meta || ''
  }
}

export const getExportSceneGroupLabel = (text, group) => (
  text.sceneGroups?.[group.id] || group.label || group.id
)

export const getExportPresetDisplay = (text, preset) => {
  if (preset.id !== 'custom') return preset

  return {
    ...preset,
    label: text.customSize,
    size: text.manualSize
  }
}
